DECK = [
    # ── NOUNS ──────────────────────────────────────────────────────────────────
    {"word":"el agasajo","type":"noun","gender":"masculine","definition":"warm welcome, treat, gift","example":"Les prepararon un agasajo especial a los invitados cuando llegaron al rancho."},
    {"word":"el albur","type":"noun","gender":"masculine","definition":"wordplay, double entendre (Mexico); also risk/chance","example":"Los albures son parte importante del humor popular mexicano cotidiano."},
    {"word":"el alboroto","type":"noun","gender":"masculine","definition":"uproar, commotion, racket","example":"El alboroto en la calle nos despertó a todos en plena madrugada."},
    {"word":"el aliciente","type":"noun","gender":"masculine","definition":"incentive, attraction, lure","example":"El bono de fin de año es el principal aliciente para quedarse en esa empresa."},
    {"word":"el alivio","type":"noun","gender":"masculine","definition":"relief, alleviation","example":"Fue un alivio saber que todos habían llegado sanos y salvos a su casa."},
    {"word":"el apego","type":"noun","gender":"masculine","definition":"attachment, fondness, bond","example":"Su apego a las tradiciones familiares es muy profundo y difícil de cambiar."},
    {"word":"el arrebato","type":"noun","gender":"masculine","definition":"outburst, fit of rage, sudden impulse","example":"En un arrebato de coraje dijo cosas de las que luego se arrepintió mucho."},
    {"word":"el asombro","type":"noun","gender":"masculine","definition":"amazement, astonishment","example":"El asombro en su cara al ver el paisaje de Oaxaca era completamente genuino."},
    {"word":"el atajo","type":"noun","gender":"masculine","definition":"shortcut","example":"Tomamos un atajo por el cerro y llegamos mucho antes de lo que esperábamos."},
    {"word":"el atrevimiento","type":"noun","gender":"masculine","definition":"boldness, audacity, nerve","example":"Tuvo el atrevimiento de contradecir al jefe delante de todos sus compañeros."},
    {"word":"el augurio","type":"noun","gender":"masculine","definition":"omen, augury, portent","example":"Las nubes oscuras eran un mal augurio para la cosecha de ese año en el campo."},
    {"word":"el bochorno","type":"noun","gender":"masculine","definition":"muggy heat, embarrassment, shame","example":"El bochorno del verano en Veracruz hacía casi imposible trabajar sin ventilador."},
    {"word":"el cabo","type":"noun","gender":"masculine","definition":"end, tip; al cabo de — after","example":"Al cabo de tres semanas sin noticias decidieron hablar con las autoridades."},
    {"word":"el cariz","type":"noun","gender":"masculine","definition":"look, aspect, way things are going","example":"El asunto tomó un cariz muy serio cuando llegaron los abogados al acuerdo."},
    {"word":"el caudal","type":"noun","gender":"masculine","definition":"flow, volume of water, wealth, abundance","example":"El caudal del río Grijalva bajó mucho durante los meses de sequía severa."},
    {"word":"el celo","type":"noun","gender":"masculine","definition":"zeal, jealousy, diligence","example":"Cumplió sus obligaciones con un celo que fue reconocido por toda la comunidad."},
    {"word":"el cometido","type":"noun","gender":"masculine","definition":"task, mission, duty","example":"Su cometido era garantizar que nadie saliera del edificio sin identificarse."},
    {"word":"el chisme","type":"noun","gender":"masculine","definition":"gossip, piece of gossip, trinket","example":"El chisme se extendió por toda la colonia antes de que ella pudiera aclararlo."},
    {"word":"el desasosiego","type":"noun","gender":"masculine","definition":"unease, restlessness, anxiety","example":"Un profundo desasosiego le impedía dormir bien en las noches de semana."},
    {"word":"el descaro","type":"noun","gender":"masculine","definition":"nerve, cheek, shamelessness","example":"Tuvo el descaro de llegar sin avisar a la boda de sus vecinos de la cuadra."},
    {"word":"el desconcierto","type":"noun","gender":"masculine","definition":"bewilderment, confusion, disarray","example":"El desconcierto fue total cuando llegaron los resultados que nadie esperaba."},
    {"word":"el desgaste","type":"noun","gender":"masculine","definition":"wear, erosion, attrition","example":"El desgaste de cuidar a un familiar enfermo por años es muy pesado emocionalmente."},
    {"word":"el desvarío","type":"noun","gender":"masculine","definition":"delirium, raving, nonsense, whim","example":"Sus palabras sonaban a puro desvarío después de tantas horas sin dormir nada."},
    {"word":"el embrollo","type":"noun","gender":"masculine","definition":"muddle, tangle, mess, fix","example":"Se metió en un buen embrollo al firmar ese contrato sin leerlo con cuidado."},
    {"word":"el empeño","type":"noun","gender":"masculine","definition":"determination, effort, insistence","example":"Con mucho empeño y dedicación logró superar todos los obstáculos del camino."},
    {"word":"el encono","type":"noun","gender":"masculine","definition":"rancor, bitterness, spite","example":"El encono entre las dos familias venía de un pleito de tierras de hace décadas."},
    {"word":"el engaño","type":"noun","gender":"masculine","definition":"deception, trick, fraud","example":"Descubrir el engaño fue un golpe muy duro para toda la familia reunida."},
    {"word":"el estorbo","type":"noun","gender":"masculine","definition":"hindrance, nuisance, obstacle","example":"Esa caja en medio del pasillo es un estorbo para cualquiera que quiera pasar."},
    {"word":"el estrago","type":"noun","gender":"masculine","definition":"havoc, devastation, damage","example":"Las heladas tardías causaron estragos en los cultivos de maíz de la región."},
    {"word":"el fingimiento","type":"noun","gender":"masculine","definition":"pretense, feigning, sham","example":"Su tristeza no era ningún fingimiento sino un dolor muy genuino y real."},
    {"word":"el forcejeo","type":"noun","gender":"masculine","definition":"struggle, scuffle, tussle","example":"Hubo un forcejeo antes de que los elementos lograran controlar la situación."},
    {"word":"el hastío","type":"noun","gender":"masculine","definition":"weariness, boredom, deep disgust","example":"El hastío de la rutina diaria lo llevó a buscar un cambio de vida radical."},
    {"word":"el hito","type":"noun","gender":"masculine","definition":"milestone, landmark, turning point","example":"La Revolución Mexicana fue un hito que definió el rumbo del país para siempre."},
    {"word":"el indicio","type":"noun","gender":"masculine","definition":"sign, indication, clue, trace","example":"No había ningún indicio de que hubiera alguien en la casa esa noche oscura."},
    {"word":"el ímpetu","type":"noun","gender":"masculine","definition":"impetus, force, drive, momentum","example":"El ímpetu con el que emprendió el negocio fue algo que nadie había visto antes."},
    {"word":"el malestar","type":"noun","gender":"masculine","definition":"unease, discomfort, discontent","example":"Sintió un malestar que le obligó a retirarse de la junta antes de que terminara."},
    {"word":"el malentendido","type":"noun","gender":"masculine","definition":"misunderstanding","example":"Todo fue un malentendido que se aclaró con una sola plática honesta y directa."},
    {"word":"el menoscabo","type":"noun","gender":"masculine","definition":"harm, detriment, damage to reputation","example":"Sus declaraciones causaron un grave menoscabo a la imagen del partido político."},
    {"word":"el perjuicio","type":"noun","gender":"masculine","definition":"harm, damage, detriment","example":"El retraso causó un serio perjuicio económico a todos los involucrados en el trato."},
    {"word":"el pesar","type":"noun","gender":"masculine","definition":"grief, sorrow, regret","example":"Se fue con mucho pesar, sabiendo que no volvería a ver ese rancho tan querido."},
    {"word":"el pretexto","type":"noun","gender":"masculine","definition":"pretext, excuse","example":"Siempre encontraba un pretexto para no ir a las reuniones de la familia extensa."},
    {"word":"el quebranto","type":"noun","gender":"masculine","definition":"grief, hardship, loss, setback","example":"La muerte de su padre fue un quebranto del que tardó muchos años en reponerse."},
    {"word":"el recelo","type":"noun","gender":"masculine","definition":"mistrust, suspicion, wariness","example":"Les miraba con recelo desde que le robaron la cartera en el metro del DF."},
    {"word":"el recodo","type":"noun","gender":"masculine","definition":"bend, turn in a road or river","example":"Al doblar el recodo del camino de terracería apareció el pueblo de repente."},
    {"word":"el reparo","type":"noun","gender":"masculine","definition":"objection, qualm, scruple, reservation","example":"No tuvo ningún reparo en decir exactamente lo que pensaba de toda la situación."},
    {"word":"el resquicio","type":"noun","gender":"masculine","definition":"crack, loophole, glimmer, slim chance","example":"Encontraron un resquicio en la ley que les permitió evitar la multa del SAT."},
    {"word":"el rezago","type":"noun","gender":"masculine","definition":"lag, backwardness, falling behind","example":"El rezago educativo en zonas rurales del sur sigue siendo un problema grave."},
    {"word":"el sosiego","type":"noun","gender":"masculine","definition":"calm, peace, tranquility","example":"Encontró el sosiego que buscaba en un pueblito de la sierra de Guerrero."},
    {"word":"el tedio","type":"noun","gender":"masculine","definition":"tedium, boredom, ennui","example":"El tedio de las tardes sin nada que hacer en el pueblo se le hacía insoportable."},
    {"word":"el titubeo","type":"noun","gender":"masculine","definition":"hesitation, wavering, stammering","example":"Aceptó el cargo sin ningún titubeo, convencido de que estaba listo para eso."},
    {"word":"el trasiego","type":"noun","gender":"masculine","definition":"hustle and bustle, coming and going","example":"El trasiego en el Zócalo a primera hora de la mañana es impresionante siempre."},
    {"word":"el tuétano","type":"noun","gender":"masculine","definition":"marrow; hasta los tuétanos — to the core","example":"El frío de la madrugada en el altiplano le calaba hasta los tuétanos sin remedio."},
    {"word":"el vaivén","type":"noun","gender":"masculine","definition":"swaying, fluctuation, ups and downs","example":"El vaivén del peso ha golpeado a muchas familias trabajadoras en estos años."},
    {"word":"la añoranza","type":"noun","gender":"feminine","definition":"longing, nostalgia, yearning","example":"La añoranza del pueblo lo acompañó durante todos sus años viviendo en el norte."},
    {"word":"la artimaña","type":"noun","gender":"feminine","definition":"trick, ruse, cunning device","example":"Usó toda clase de artimañas para evitar pagar lo que debía al casero."},
    {"word":"la astucia","type":"noun","gender":"feminine","definition":"cunning, shrewdness, craftiness","example":"Con mucha astucia logró salir bien de aquella situación tan comprometida."},
    {"word":"la cavilación","type":"noun","gender":"feminine","definition":"brooding, deep thought, pondering","example":"Después de mucha cavilación decidió rechazar la oferta de trabajo en el norte."},
    {"word":"la cizaña","type":"noun","gender":"feminine","definition":"discord; meter cizaña — to sow discord","example":"Siempre andaba metiendo cizaña entre los vecinos con sus comentarios malintencionados."},
    {"word":"la congoja","type":"noun","gender":"feminine","definition":"anguish, grief, distress","example":"La congoja que sentía al despedirse en el aeropuerto era difícil de disimular."},
    {"word":"la contrariedad","type":"noun","gender":"feminine","definition":"setback, annoyance, vexation","example":"Las pequeñas contrariedades del día le afectaban demasiado para su propio bien."},
    {"word":"la coyuntura","type":"noun","gender":"feminine","definition":"juncture, situation, opportunity","example":"Aprovechó la coyuntura para lanzar su negocio cuando el mercado lo permitía."},
    {"word":"la cuita","type":"noun","gender":"feminine","definition":"trouble, worry, sorrow, woe","example":"Le contó sus cuitas a su comadre sin guardarse nada en esa larga plática."},
    {"word":"la desidia","type":"noun","gender":"feminine","definition":"slackness, apathy, negligence","example":"La desidia con la que hacía su trabajo terminó costándole el empleo finalmente."},
    {"word":"la destreza","type":"noun","gender":"feminine","definition":"skill, dexterity, expertise","example":"La destreza de los artesanos de Taxco se nota en cada pieza de plata que hacen."},
    {"word":"la dicha","type":"noun","gender":"feminine","definition":"happiness, good fortune, joy","example":"La dicha de tener buena salud es algo que muchos solo valoran cuando la pierden."},
    {"word":"la disyuntiva","type":"noun","gender":"feminine","definition":"dilemma, either/or choice","example":"Se encontraba ante una disyuntiva muy difícil y cualquier camino tenía sus riesgos."},
    {"word":"la encrucijada","type":"noun","gender":"feminine","definition":"crossroads, dilemma","example":"El país estaba en una encrucijada que definiría los próximos veinte años de historia."},
    {"word":"la farsa","type":"noun","gender":"feminine","definition":"farce, sham, pretense","example":"Todo el proceso fue una farsa montada para aparentar que había democracia interna."},
    {"word":"la flaqueza","type":"noun","gender":"feminine","definition":"weakness, failing, frailty","example":"Su mayor flaqueza era no poder decirle que no a nadie sin sentirse mal después."},
    {"word":"la holgura","type":"noun","gender":"feminine","definition":"ease, comfort, financial ease","example":"Vivían con cierta holgura gracias al negocio de abarrotes que heredaron del abuelo."},
    {"word":"la huella","type":"noun","gender":"feminine","definition":"footprint, trace, mark, lasting impression","example":"El terremoto del 85 dejó una huella imborrable en la memoria de los chilangos."},
    {"word":"la índole","type":"noun","gender":"feminine","definition":"nature, character, kind, sort","example":"Los problemas de índole personal no deben mezclarse con las cuestiones laborales."},
    {"word":"la inquina","type":"noun","gender":"feminine","definition":"deep dislike, grudge, animosity","example":"Le tenía una inquina desde aquel pleito de años atrás que nunca había olvidado."},
    {"word":"la lozanía","type":"noun","gender":"feminine","definition":"freshness, vigor, bloom, vitality","example":"La lozanía de su piel delataba que cuidaba mucho su salud y su manera de vivir."},
    {"word":"la mezquindad","type":"noun","gender":"feminine","definition":"meanness, pettiness, stinginess","example":"La mezquindad con la que trataba a sus trabajadores le ganó muy mala reputación."},
    {"word":"la murmuración","type":"noun","gender":"feminine","definition":"gossiping, backbiting","example":"Las murmuraciones de la vecindad no tardaron en llegarle por conducto de su mamá."},
    {"word":"la parsimonia","type":"noun","gender":"feminine","definition":"calmness, deliberateness, unhurried pace","example":"Tomó la noticia con una parsimonia que dejó a todos los presentes sin palabras."},
    {"word":"la porfía","type":"noun","gender":"feminine","definition":"stubbornness, persistence, obstinacy","example":"Su porfía en defender esa postura acabó alejándolo de la mayoría del grupo."},
    {"word":"la querencia","type":"noun","gender":"feminine","definition":"deep attachment to a place, homing instinct","example":"La querencia por su pueblo siempre lo trajo de regreso después de años fuera."},
    {"word":"la quimera","type":"noun","gender":"feminine","definition":"pipe dream, illusion, impossible dream","example":"Creer que todo cambiaría de un día para otro era pura quimera sin fundamento."},
    {"word":"la rencilla","type":"noun","gender":"feminine","definition":"petty quarrel, squabble, ongoing dispute","example":"Una vieja rencilla entre compadres envenenó el ambiente de toda la comunidad."},
    {"word":"la sandez","type":"noun","gender":"feminine","definition":"foolishness, nonsense, stupidity","example":"No tengo tiempo para andar escuchando sandeces de gente que no sabe nada."},
    {"word":"la soberbia","type":"noun","gender":"feminine","definition":"arrogance, pride, haughtiness","example":"Su soberbia le impedía reconocer cuándo se había equivocado delante de los demás."},
    {"word":"la tesitura","type":"noun","gender":"feminine","definition":"situation, difficult circumstances one finds oneself in","example":"En esa tesitura tan complicada cualquier decisión iba a tener consecuencias serias."},
    {"word":"la tirria","type":"noun","gender":"feminine","definition":"strong dislike, grudge, aversion","example":"Le tenía una tirria enorme desde que le hizo esa jugarreta años atrás en el trabajo."},
    {"word":"la tozudez","type":"noun","gender":"feminine","definition":"stubbornness, pig-headedness","example":"Su tozudez le impedía reconocer que estaba equivocado aunque la evidencia fuera clara."},
    {"word":"la trifulca","type":"noun","gender":"feminine","definition":"row, brawl, rumpus, heated argument","example":"Una trifulca entre vecinos obligó a intervenir a la policía preventiva del municipio."},
    {"word":"la veleidad","type":"noun","gender":"feminine","definition":"fickleness, whim, inconstancy","example":"Sus veleidadades políticas le quitaron credibilidad ante los electores de su distrito."},
    {"word":"la zozobra","type":"noun","gender":"feminine","definition":"anxiety, worry, anguish","example":"La zozobra ante el futuro incierto se sentía en todos los sectores de la sociedad."},

    # ── VERBS ──────────────────────────────────────────────────────────────────
    {"word":"abatir","type":"verb","gender":"","definition":"to knock down, to shoot down, to depress","example":"Las malas noticias lo abatieron completamente y estuvo días sin querer salir."},
    {"word":"acuciar","type":"verb","gender":"","definition":"to urge, to press, to afflict urgently","example":"La necesidad de dinero lo acuciaba y no lo dejaba pensar en otra cosa."},
    {"word":"adolecer de","type":"verb","gender":"","definition":"to suffer from, to be lacking in","example":"El proyecto adolece de una falta grave de planeación desde el principio."},
    {"word":"afanarse","type":"verb","gender":"","definition":"to strive hard, to toil, to busy oneself","example":"Se afanó toda su vida para que sus hijos tuvieran lo que él no pudo tener."},
    {"word":"ahondar","type":"verb","gender":"","definition":"to deepen, to go deeper into a subject","example":"Ahondó en el tema hasta descubrir verdades que muy pocos querían reconocer."},
    {"word":"alardear","type":"verb","gender":"","definition":"to boast, to show off, to brag","example":"No perdía ocasión de alardear de sus contactos con funcionarios del gobierno."},
    {"word":"alentar","type":"verb","gender":"","definition":"to encourage, to give hope, to foster","example":"Sus palabras me alentaron a seguir adelante cuando ya pensaba en rendirme."},
    {"word":"amedrentar","type":"verb","gender":"","definition":"to intimidate, to frighten, to cow","example":"Sus amenazas no lograron amedrentarlo ni hacerlo cambiar de postura en nada."},
    {"word":"amenguar","type":"verb","gender":"","definition":"to diminish, to lessen, to reduce gradually","example":"Con el tiempo se fue amengüando el dolor que sentía por esa separación tan difícil."},
    {"word":"anhelar","type":"verb","gender":"","definition":"to long for, to yearn for, to desire deeply","example":"Anhelaba una vida tranquila lejos del ruido y el estrés de la Ciudad de México."},
    {"word":"antojarse","type":"verb","gender":"","definition":"to feel like, to have a craving for, to seem","example":"Se me antoja que todo esto va a acabar peor de lo que pensamos ahorita."},
    {"word":"apearse","type":"verb","gender":"","definition":"to get off, to dismount, to back down from a position","example":"No se apea de su postura por más que le expliquen que está equivocado."},
    {"word":"aplacar","type":"verb","gender":"","definition":"to placate, to appease, to calm down","example":"Intentó aplacar su coraje con palabras amables pero no lo pudo lograr."},
    {"word":"atesorar","type":"verb","gender":"","definition":"to treasure, to accumulate, to cherish","example":"Atesora una colección de recuerdos de todos sus viajes por la república mexicana."},
    {"word":"avenir","type":"verb","gender":"","definition":"to reconcile, to come to terms, to agree","example":"Al final lograron avenirse después de meses de pleitos y desacuerdos constantes."},
    {"word":"ceñirse","type":"verb","gender":"","definition":"to stick to, to keep to, to confine oneself to","example":"Cíñete al tema sin irte por las ramas o perdemos el hilo de la conversación."},
    {"word":"cobijar","type":"verb","gender":"","definition":"to shelter, to take in, to give refuge","example":"El albergue cobija a decenas de migrantes que vienen de paso por la frontera."},
    {"word":"cohibir","type":"verb","gender":"","definition":"to inhibit, to make self-conscious, to hold back","example":"Su presencia lo cohibía tanto que casi no podía articular bien las palabras."},
    {"word":"colmar","type":"verb","gender":"","definition":"to fill to the brim, to fulfill, to shower with","example":"Lo colmaron de felicitaciones después de su presentación ante toda la empresa."},
    {"word":"condolerse","type":"verb","gender":"","definition":"to feel sorry for, to express sympathy","example":"Se condolió de corazón por la pérdida que acababa de sufrir su vecina."},
    {"word":"cotejar","type":"verb","gender":"","definition":"to compare, to collate, to check one against another","example":"Cotejó los dos contratos y encontró varias diferencias que nadie había notado."},
    {"word":"desdecirse","type":"verb","gender":"","definition":"to go back on one's word, to retract what was said","example":"Se desdijo de todo lo que había prometido sin dar ninguna explicación válida."},
    {"word":"desdeñar","type":"verb","gender":"","definition":"to disdain, to scorn, to look down on","example":"Desdeñó la oferta sin tomarse la molestia de analizarla con seriedad."},
    {"word":"desentrañar","type":"verb","gender":"","definition":"to unravel, to get to the bottom of, to figure out","example":"Le llevó meses desentrañar el asunto que tenía envuelto al ejido entero."},
    {"word":"desistir","type":"verb","gender":"","definition":"to desist, to give up, to abandon an effort","example":"Desistió de su intento cuando se dio cuenta de que nadie lo iba a apoyar."},
    {"word":"despuntar","type":"verb","gender":"","definition":"to stand out, to excel, to show promise","example":"Desde chamaco despuntaba entre sus compañeros por su manera de razonar."},
    {"word":"disuadir","type":"verb","gender":"","definition":"to dissuade, to deter, to talk someone out of something","example":"Intentaron disuadirlo de irse al norte pero no pudieron convencerlo de quedarse."},
    {"word":"eludir","type":"verb","gender":"","definition":"to elude, to dodge, to get out of something","example":"Eludió todas las preguntas comprometedoras con una habilidad que sorprendió a todos."},
    {"word":"empecinarse","type":"verb","gender":"","definition":"to persist stubbornly, to dig one's heels in","example":"Se empecinó en su error aunque toda la familia le decía lo contrario siempre."},
    {"word":"enfrascarse","type":"verb","gender":"","definition":"to become engrossed in, to get absorbed by","example":"Se enfrascó tanto en la lectura que no escuchó cuando le llamaron a cenar."},
    {"word":"engreírse","type":"verb","gender":"","definition":"to become conceited, to get big-headed, to get cocky","example":"El éxito lo engreió tanto que acabó perdiendo a todos sus cuates más cercanos."},
    {"word":"enmendarse","type":"verb","gender":"","definition":"to mend one's ways, to reform, to correct oneself","example":"Prometió enmendarse pero los mismos vicios volvieron al poco tiempo de nuevo."},
    {"word":"entrañar","type":"verb","gender":"","definition":"to entail, to involve, to carry within it","example":"Esa decisión entraña un riesgo muy grande que no conviene ignorar nada."},
    {"word":"escabullirse","type":"verb","gender":"","definition":"to slip away, to sneak off, to wriggle out","example":"Se escabulló de la reunión sin que nadie se diera cuenta de que se había ido."},
    {"word":"escarmentar","type":"verb","gender":"","definition":"to learn one's lesson, to wise up after a bad experience","example":"Espero que con esto hayas escarmentado y no vuelvas a cometer el mismo error."},
    {"word":"hostigar","type":"verb","gender":"","definition":"to harass, to pester, to badger persistently","example":"Sus rivales no dejaban de hostigarlo con acusaciones que no tenían sustento."},
    {"word":"incurrir","type":"verb","gender":"","definition":"to incur, to fall into, to be guilty of","example":"Al mentir incurrió en una contradicción que echó por tierra toda su coartada."},
    {"word":"instar","type":"verb","gender":"","definition":"to urge, to press, to call upon someone to act","example":"Lo instaron a renunciar pero se negó a dejar el cargo sin dar pelea primero."},
    {"word":"intuir","type":"verb","gender":"","definition":"to sense, to intuit, to have a gut feeling about","example":"Intuía que algo andaba mal mucho antes de que alguien le dijera cualquier cosa."},
    {"word":"jadear","type":"verb","gender":"","definition":"to pant, to gasp for breath","example":"Llegó jadeando después de correr varias cuadras para alcanzar el metro."},
    {"word":"malbaratar","type":"verb","gender":"","definition":"to squander, to sell off cheaply, to waste resources","example":"Malbarató todo lo que heredó en negocios que no funcionaron para nada."},
    {"word":"menoscabar","type":"verb","gender":"","definition":"to harm, to diminish, to undermine","example":"Sus declaraciones menoscabaron la reputación que había construido con tanto esfuerzo."},
    {"word":"mofarse","type":"verb","gender":"","definition":"to mock, to jeer at, to make fun of","example":"Se mofaba del trabajo de sus compañeros sin que nadie se atreviera a reclamarle."},
    {"word":"obstinarse","type":"verb","gender":"","definition":"to be obstinate, to persist stubbornly against all reason","example":"Se obstinó en su versión aunque los hechos claramente la contradecían por completo."},
    {"word":"paladear","type":"verb","gender":"","definition":"to savor, to relish, to taste slowly and with pleasure","example":"Paladeó cada sorbo del mezcal artesanal como si fuera el último que tomaría."},
    {"word":"pecar","type":"verb","gender":"","definition":"to sin, to err on the side of, to be guilty of (excess)","example":"Si hay que pecar de algo, que sea de demasiado honesto y directo con la gente."},
    {"word":"porfiar","type":"verb","gender":"","definition":"to persist, to argue stubbornly, to keep insisting","example":"Porfió tanto en su punto de vista que terminó convenciendo a los más escépticos."},
    {"word":"presagiar","type":"verb","gender":"","definition":"to presage, to forebode, to foreshadow","example":"Aquellas señales presagiaban un temporal muy fuerte para la región costera."},
    {"word":"pujar","type":"verb","gender":"","definition":"to bid, to struggle, to strain with effort","example":"Pujó por el terreno en el remate hasta conseguirlo aunque pasara su presupuesto."},
    {"word":"recabar","type":"verb","gender":"","definition":"to gather, to obtain, to seek and collect","example":"Recabó toda la información necesaria antes de presentarle la propuesta al jefe."},
    {"word":"recaer","type":"verb","gender":"","definition":"to relapse, to fall again, to rest upon someone","example":"La responsabilidad siempre terminaba recayendo en los mismos de siempre."},
    {"word":"recriminar","type":"verb","gender":"","definition":"to reproach, to recriminate, to blame","example":"Le recriminó no haber estado cuando más lo necesitaba en ese momento difícil."},
    {"word":"rehuir","type":"verb","gender":"","definition":"to shun, to avoid, to shy away from","example":"Rehuía el contacto con la gente desde que su salud empezó a fallarle."},
    {"word":"reñir","type":"verb","gender":"","definition":"to quarrel, to scold, to get into a fight with","example":"Riñeron por una pendejada y tardaron semanas en volver a hablarse de nuevo."},
    {"word":"reprender","type":"verb","gender":"","definition":"to reprimand, to rebuke, to tell off","example":"Lo reprendió enfrente de todos por llegar tarde sin siquiera mandar aviso."},
    {"word":"rezongar","type":"verb","gender":"","definition":"to grumble, to mutter, to grouse under one's breath","example":"Rezongaba por lo bajo pero nunca se atrevía a reclamar abiertamente nada."},
    {"word":"soliviantar","type":"verb","gender":"","definition":"to stir up, to rouse, to make restless and agitated","example":"Sus palabras soliviantaron a la gente que ya estaba muy encendida de por sí."},
    {"word":"tergiversar","type":"verb","gender":"","definition":"to distort, to twist, to misrepresent what was said","example":"Tergiversó mis palabras para hacer que pareciera que yo era el culpable."},
    {"word":"traslucir","type":"verb","gender":"","definition":"to show through, to reveal, to be apparent beneath","example":"Su nerviosismo se traslucía en cada gesto aunque intentara disimularlo bien."},
    {"word":"ufanarse","type":"verb","gender":"","definition":"to pride oneself on, to boast, to revel in","example":"Se ufanaba de sus contactos cada vez que tenía la mínima oportunidad de hacerlo."},
    {"word":"vacilar","type":"verb","gender":"","definition":"to hesitate, to waver; also to tease (Mexican slang)","example":"Vaciló un buen rato antes de firmar el contrato que le cambiaría la vida entera."},
    {"word":"zahondar","type":"verb","gender":"","definition":"to dig deep, to go thoroughly into a problem","example":"Hay que zahondar en las causas de raíz y no quedarse solo en lo superficial."},
    {"word":"abochornarse","type":"verb","gender":"","definition":"to be embarrassed, to feel ashamed, to turn red","example":"Se abochornó cuando todos voltearon a verlo al caérsele la charola en el comedor."},
    {"word":"aborrecer","type":"verb","gender":"","definition":"to loathe, to detest, to abhor","example":"Aborrecía las juntas largas que no llegaban a ningún acuerdo concreto nunca."},
    {"word":"acallar","type":"verb","gender":"","definition":"to silence, to hush, to quieten criticism","example":"Sus argumentos no lograron acallar las críticas que llegaban desde todos lados."},
    {"word":"acatar","type":"verb","gender":"","definition":"to comply with, to abide by, to respect a rule or order","example":"Todos tenemos que acatar las normas aunque no estemos de acuerdo con ellas."},
    {"word":"achacarse","type":"verb","gender":"","definition":"to attribute to, to blame on, to put down to","example":"Le achacó su mal humor a la falta de sueño de los últimos días de trabajo."},
    {"word":"acometer","type":"verb","gender":"","definition":"to undertake, to tackle boldly, to assail","example":"Acometió la reforma del sistema con una energía que sorprendió a todo el equipo."},
    {"word":"acongojar","type":"verb","gender":"","definition":"to distress, to cause deep anguish, to grieve","example":"La noticia lo acongojó de tal manera que no pudo hablar durante varias horas."},
    {"word":"adueñarse","type":"verb","gender":"","definition":"to take over, to seize, to become master of","example":"El miedo se adueñó de todos en el momento en que cortaron la luz de golpe."},
    {"word":"afligir","type":"verb","gender":"","definition":"to afflict, to grieve, to distress deeply","example":"Le afligía mucho no poder ayudar a quienes más lo necesitaban a su alrededor."},
    {"word":"aguardar","type":"verb","gender":"","definition":"to wait for, to await, to expect patiently","example":"Aguardó varias horas sin perder la calma ni la esperanza de que llegara."},
    {"word":"ahogar","type":"verb","gender":"","definition":"to drown, to stifle, to choke, to suppress","example":"El ruido del tráfico de la ciudad ahogaba cualquier intento de platicar tranquilo."},
    {"word":"albergar","type":"verb","gender":"","definition":"to harbor, to house, to cherish (hopes, feelings)","example":"Todavía albergaba la esperanza de que las cosas pudieran cambiar para bien."},
    {"word":"alegar","type":"verb","gender":"","definition":"to allege, to claim, to put forward as an argument","example":"Alegó que nadie le había avisado a tiempo de los cambios que habían acordado."},
    {"word":"amparar","type":"verb","gender":"","definition":"to protect, to shelter, to defend legally","example":"La ley debe amparar a los trabajadores frente a los abusos de los patrones."},
    {"word":"apaciguar","type":"verb","gender":"","definition":"to pacify, to calm things down, to appease","example":"Costó mucho apaciguar los ánimos después de ese debate tan caldeado y difícil."},
    {"word":"apiadarse","type":"verb","gender":"","definition":"to take pity on, to feel compassion for","example":"Nadie se apiadó de él cuando más lo necesitaba y eso lo marcó de por vida."},
    {"word":"aplazar","type":"verb","gender":"","definition":"to postpone, to defer, to put off until later","example":"Decidieron aplazar la reunión hasta tener todos los datos bien sobre la mesa."},
    {"word":"apremiar","type":"verb","gender":"","definition":"to urge, to press, to be pressing and urgent","example":"El tiempo apremiaba y todavía faltaban muchas decisiones importantes por tomar."},
    {"word":"arrastrar","type":"verb","gender":"","definition":"to drag, to carry along, to suffer from for a long time","example":"Arrastraba esa deuda desde hace años y le impedía hacer cualquier plan a futuro."},
    {"word":"arrepentirse","type":"verb","gender":"","definition":"to regret, to repent, to be sorry about something","example":"Se arrepintió de haber dicho eso en cuanto vio cómo reaccionaron los demás."},
    {"word":"asimilar","type":"verb","gender":"","definition":"to assimilate, to absorb, to take in and process","example":"Le tomó tiempo asimilar todo lo que había pasado en tan pocas horas ese día."},
    {"word":"atenerse","type":"verb","gender":"","definition":"to abide by, to stick to, to face the consequences","example":"Quien no respete las reglas tendrá que atenerse a lo que le corresponda."},
    {"word":"atenuar","type":"verb","gender":"","definition":"to attenuate, to lessen, to tone down","example":"Sus disculpas atenuaron en algo el daño que habían causado sus declaraciones."},
    {"word":"cernirse","type":"verb","gender":"","definition":"to loom over, to hang over, to hover threateningly","example":"Una amenaza de cierre se cernía sobre la planta desde hacía varios meses ya."},
    {"word":"comprometerse","type":"verb","gender":"","definition":"to commit oneself, to make a promise, to get engaged","example":"Se comprometió a entregar el informe antes del viernes sin ninguna excusa."},
    {"word":"concebir","type":"verb","gender":"","definition":"to conceive, to think up, to be able to imagine","example":"No podía concebir que alguien de confianza pudiera actuar de manera tan desleal."},
    {"word":"conllevar","type":"verb","gender":"","definition":"to entail, to involve, to carry with it as a consequence","example":"Aceptar ese puesto conlleva renunciar a gran parte de tu vida personal y familiar."},
    {"word":"consentir","type":"verb","gender":"","definition":"to allow, to consent to, to let something slide","example":"No puedo consentir que sigan cometiéndose esos errores sin que haya consecuencias."},
    {"word":"contraer","type":"verb","gender":"","definition":"to contract, to catch an illness, to take on debt","example":"Contrajo una deuda enorme para poner el negocio que siempre había soñado tener."},
    {"word":"convenir","type":"verb","gender":"","definition":"to suit, to be advisable, to agree upon terms","example":"Conviene revisar bien el contrato antes de firmarlo para no llevarse sorpresas."},
    {"word":"dar pie a","type":"verb","gender":"","definition":"to give rise to, to provide grounds for, to lead to","example":"Su descuido dio pie a una serie de malentendidos que tardaron en aclararse bien."},
    {"word":"debilitar","type":"verb","gender":"","definition":"to weaken, to undermine, to debilitate gradually","example":"Años de conflictos internos habían debilitado mucho la unidad del movimiento."},
    {"word":"declinar","type":"verb","gender":"","definition":"to decline, to turn down politely, to wane","example":"Declinó la invitación con mucha cortesía alegando compromisos previos ineludibles."},
    {"word":"demorarse","type":"verb","gender":"","definition":"to be delayed, to take too long, to tarry","example":"Se demoró más de lo que debía y llegó cuando ya casi todo había terminado."},
    {"word":"desencadenar","type":"verb","gender":"","definition":"to trigger, to unleash, to set off a chain reaction","example":"Una chispa pequeña desencadenó una crisis que nadie en la empresa había anticipado."},
    {"word":"desengañarse","type":"verb","gender":"","definition":"to become disillusioned, to face reality as it is","example":"Tardó mucho en desengañarse y ver la situación tal como realmente era."},
    {"word":"desprenderse","type":"verb","gender":"","definition":"to let go of, to follow from, to be detached from","example":"De sus palabras se desprende que no tiene ninguna intención de renunciar todavía."},
    {"word":"dimanar","type":"verb","gender":"","definition":"to stem from, to arise from, to originate in","example":"Todos esos problemas dimanan de una pésima planeación desde el inicio del proyecto."},
    {"word":"discernir","type":"verb","gender":"","definition":"to discern, to distinguish, to tell one thing from another","example":"Hay que saber discernir entre lo urgente y lo que verdaderamente importa a largo plazo."},
    {"word":"disentir","type":"verb","gender":"","definition":"to dissent, to disagree, to hold a different view","example":"Disiento de tu análisis aunque reconozco que hay algunos puntos válidos ahí."},
    {"word":"distanciarse","type":"verb","gender":"","definition":"to distance oneself, to grow apart from someone","example":"Con el paso del tiempo se fue distanciando de quienes habían sido sus mejores cuates."},
    {"word":"ejercer","type":"verb","gender":"","definition":"to exercise, to practise a profession, to exert influence","example":"Lleva más de veinte años ejerciendo la medicina en una comunidad rural del estado."},
    {"word":"encauzar","type":"verb","gender":"","definition":"to channel, to direct, to guide toward a goal","example":"Lograron encauzar la energía del equipo hacia objetivos mucho más productivos."},
    {"word":"enmascarar","type":"verb","gender":"","definition":"to mask, to disguise, to conceal under a false appearance","example":"Sus buenos modales enmascaraban una frialdad que muy pocos llegaban a percibir."},
    {"word":"enredarse","type":"verb","gender":"","definition":"to get tangled up in, to get involved in a mess","example":"Se enredó en una discusión que no llevaba a ningún lado y perdió el tiempo."},
    {"word":"extraer","type":"verb","gender":"","definition":"to extract, to draw out, to derive a lesson or conclusion","example":"De esa experiencia extrajo enseñanzas que le fueron útiles durante muchos años."},
    {"word":"fingir","type":"verb","gender":"","definition":"to pretend, to feign, to fake a feeling or condition","example":"Fingió no entender la pregunta para ganar tiempo y pensar bien su respuesta."},
    {"word":"forjarse","type":"verb","gender":"","definition":"to forge oneself, to build up a reputation or character","example":"Se forjó una buena reputación a base de años de trabajo honesto y constante."},
    {"word":"granjearse","type":"verb","gender":"","definition":"to earn, to win, to gain affection or respect","example":"Se ganó el respeto de todos con su manera de comportarse siempre con integridad."},
    {"word":"imperar","type":"verb","gender":"","definition":"to prevail, to reign, to be the dominant force","example":"En esa época imperaba una mentalidad muy conservadora en toda la clase política."},
    {"word":"imponerse","type":"verb","gender":"","definition":"to prevail, to assert oneself, to win out","example":"Al final se impuso el criterio de los más experimentados del grupo de trabajo."},
    {"word":"indagar","type":"verb","gender":"","definition":"to investigate, to inquire into, to look into carefully","example":"Indagó en los archivos del municipio hasta encontrar la prueba que necesitaba."},
    {"word":"infundir","type":"verb","gender":"","definition":"to instill, to inspire, to infuse with a feeling","example":"Sus palabras infundieron ánimo a todos los que ya estaban a punto de darse por vencidos."},
    {"word":"lidiar","type":"verb","gender":"","definition":"to deal with, to cope with, to contend with difficulty","example":"Tuvo que lidiar con situaciones muy pesadas a lo largo de toda su trayectoria."},
    {"word":"maquillar","type":"verb","gender":"","definition":"to make up, to disguise, to gloss over a problem","example":"Intentaron maquillar las cifras para que el balance pareciera menos desastroso."},
    {"word":"mermar","type":"verb","gender":"","definition":"to reduce, to diminish, to deplete little by little","example":"La falta de inversión fue mermando la calidad del servicio con el paso del tiempo."},
    {"word":"omitir","type":"verb","gender":"","definition":"to omit, to leave out, to fail to mention deliberately","example":"Omitió a propósito los datos que contradecían su argumento central del informe."},
    {"word":"paliar","type":"verb","gender":"","definition":"to alleviate, to mitigate, to ease without fully solving","example":"Las becas no alcanzan para paliar la situación de tantas familias en pobreza."},
    {"word":"padecer","type":"verb","gender":"","definition":"to suffer from, to endure, to be afflicted by","example":"Padecía una enfermedad crónica que le impedía llevar una vida completamente normal."},
    {"word":"persistir","type":"verb","gender":"","definition":"to persist, to continue, to remain despite efforts","example":"El problema persiste a pesar de todas las medidas que se han tomado hasta ahora."},
    {"word":"precipitarse","type":"verb","gender":"","definition":"to rush, to act rashly, to make a hasty decision","example":"Se precipitó al tomar esa decisión sin haber analizado todas las opciones posibles."},
    {"word":"prevalecer","type":"verb","gender":"","definition":"to prevail, to triumph, to win out in the end","example":"Al final prevaleció el sentido común sobre los intereses particulares de unos pocos."},
    {"word":"procurar","type":"verb","gender":"","definition":"to try to, to endeavor, to see to it that something happens","example":"Procura llegar a tiempo porque en esta ocasión no van a esperar a nadie más."},
    {"word":"proferir","type":"verb","gender":"","definition":"to utter, to let out, to hurl insults or threats","example":"Profirió insultos que dejaron a todos los presentes completamente helados y atónitos."},
    {"word":"propiciar","type":"verb","gender":"","definition":"to favor, to bring about, to foster conditions for","example":"El nuevo ambiente propició el acercamiento entre las dos partes que estaban peleadas."},
    {"word":"pugnar","type":"verb","gender":"","definition":"to fight, to strive, to struggle against opposition","example":"Pugnó por defender sus ideas frente a la mayoría que se oponía frontalmente."},
    {"word":"reclamar","type":"verb","gender":"","definition":"to demand, to claim, to call for what is owed","example":"Lleva años reclamando la compensación que le prometieron y nunca le han dado."},
    {"word":"reconciliarse","type":"verb","gender":"","definition":"to make up, to reconcile, to patch things up","example":"Tardaron meses en reconciliarse después de la pelea más grave que habían tenido."},
    {"word":"reponerse","type":"verb","gender":"","definition":"to recover, to get over, to bounce back","example":"Se repuso del golpe con una rapidez que sorprendió hasta a sus propios médicos."},
    {"word":"reprochar","type":"verb","gender":"","definition":"to reproach, to rebuke, to hold something against someone","example":"Le reprochó que nunca hubiera estado presente cuando de verdad lo necesitaba."},
    {"word":"resistirse","type":"verb","gender":"","definition":"to resist, to refuse, to be unwilling to accept","example":"Se resistía a admitir que las cosas habían cambiado de manera irreversible ya."},
    {"word":"retraerse","type":"verb","gender":"","definition":"to withdraw, to become reclusive, to pull back","example":"Se fue retraendo poco a poco hasta no querer salir de su casa para nada."},
    {"word":"revelar","type":"verb","gender":"","definition":"to reveal, to disclose, to bring to light","example":"Tardó años en revelar la verdad sobre lo que había pasado aquella noche oscura."},
    {"word":"rondar","type":"verb","gender":"","definition":"to hover around, to be around an age, to haunt","example":"Una sensación rara lo rondaba desde que tuvo esa última conversación con él."},
    {"word":"sortear","type":"verb","gender":"","definition":"to dodge, to get around, to navigate obstacles skillfully","example":"Sorteó todos los obstáculos con una habilidad que dejó a todos con la boca abierta."},
    {"word":"subyacer","type":"verb","gender":"","definition":"to underlie, to lie beneath the surface","example":"Subyace una desconfianza profunda que hace imposible cualquier acuerdo duradero."},
    {"word":"suponer","type":"verb","gender":"","definition":"to suppose, to mean, to represent, to entail","example":"Ese cambio supone un avance enorme para la comunidad que lo viene pidiendo años."},
    {"word":"trascender","type":"verb","gender":"","definition":"to transcend, to leak out, to go beyond boundaries","example":"La noticia trascendió a los medios antes de que pudieran controlar los daños."},
    {"word":"transigir","type":"verb","gender":"","definition":"to give in, to compromise, to yield on a point","example":"No estaba dispuesto a transigir en los temas que consideraba fundamentales para él."},
    {"word":"velar","type":"verb","gender":"","definition":"to watch over, to look after, to keep vigil","example":"Siempre veló por los intereses de su comunidad con mucha entrega y dedicación."},
    {"word":"zanjarse","type":"verb","gender":"","definition":"to be settled, to be resolved definitively once and for all","example":"El asunto se zanjó en esa junta sin necesidad de llegar a mayores problemas."},

    # ── ADJECTIVES ────────────────────────────────────────────────────────────
    {"word":"acendrado","type":"adjective","gender":"","definition":"pure, refined, deeply felt, thoroughgoing","example":"Tiene un acendrado amor por su tierra que nunca ha querido disimular ante nadie."},
    {"word":"acerbo","type":"adjective","gender":"","definition":"harsh, bitter, acerbic, cutting","example":"La crítica fue tan acerba que dejó al autor completamente desmoralizado y triste."},
    {"word":"acuciante","type":"adjective","gender":"","definition":"pressing, urgent, nagging","example":"La necesidad acuciante de vivienda digna exige que el gobierno tome medidas ya."},
    {"word":"afable","type":"adjective","gender":"","definition":"affable, pleasant, easy to talk to","example":"Era una persona muy afable con la que cualquiera podía entablar conversación fácil."},
    {"word":"aguerrido","type":"adjective","gender":"","definition":"battle-hardened, seasoned, tough and experienced","example":"Un equipo aguerrido que no se rinde aunque las circunstancias se pongan muy difíciles."},
    {"word":"alevoso","type":"adjective","gender":"","definition":"treacherous, sneaky, underhand, done by stealth","example":"Fue un golpe alevoso que nadie esperaba de alguien en quien tanto habían confiado."},
    {"word":"altivo","type":"adjective","gender":"","definition":"haughty, arrogant, lofty in manner","example":"Su mirada altiva dejaba claro que no tenía ninguna intención de ceder en nada."},
    {"word":"añejo","type":"adjective","gender":"","definition":"old, aged, mature, long-standing","example":"Los añejos rencores entre las dos familias volvieron a salir con toda su fuerza."},
    {"word":"arduo","type":"adjective","gender":"","definition":"arduous, hard, difficult, requiring great effort","example":"Fue una tarea ardua pero al final consiguieron terminarla antes del plazo dado."},
    {"word":"arisco","type":"adjective","gender":"","definition":"unfriendly, surly, prickly, hard to approach","example":"Era un hombre muy arisco que casi no hablaba ni con sus propios vecinos cercanos."},
    {"word":"avieso","type":"adjective","gender":"","definition":"crooked, twisted, malicious, with bad intentions","example":"Tenía intenciones aviesas que tardaron en quedar al descubierto para todos."},
    {"word":"baldío","type":"adjective","gender":"","definition":"waste, uncultivated, futile, done in vain","example":"Sus esfuerzos resultaron baldíos ante la indiferencia total del público convocado."},
    {"word":"baqueteado","type":"adjective","gender":"","definition":"battered, knocked about, hardened by experience","example":"Era un periodista muy baqueteado al que ya casi nada podía sorprenderlo en su trabajo."},
    {"word":"bisoño","type":"adjective","gender":"","definition":"inexperienced, green, raw, still learning the ropes","example":"Era demasiado bisoño para entender las complejidades de ese negocio tan complicado."},
    {"word":"capcioso","type":"adjective","gender":"","definition":"misleading, insidious, loaded (especially of questions)","example":"Le hicieron una pregunta capciosa para que se contradijera frente a todos los medios."},
    {"word":"ceñudo","type":"adjective","gender":"","definition":"frowning, grim, scowling, with a stern expression","example":"Entró muy ceñudo a la sala y todos supieron de inmediato que las noticias eran malas."},
    {"word":"cerril","type":"adjective","gender":"","definition":"rough, wild, stubborn as a mule, uncompromising","example":"Su actitud cerril hacía imposible llegar a ningún tipo de acuerdo con él."},
    {"word":"cicatero","type":"adjective","gender":"","definition":"stingy, mean, tight-fisted, penny-pinching","example":"Era tan cicatero que se negaba a dejar propina aunque el servicio hubiera sido excelente."},
    {"word":"circunspecto","type":"adjective","gender":"","definition":"circumspect, prudent, cautious, measured","example":"Fue muy circunspecto en sus declaraciones para no comprometerse más de lo necesario."},
    {"word":"clarividente","type":"adjective","gender":"","definition":"clear-sighted, far-sighted, perceptive about the future","example":"Fue un dirigente clarividente que anticipó los cambios que vendrían en la siguiente década."},
    {"word":"condescendiente","type":"adjective","gender":"","definition":"condescending, patronizing in manner","example":"Su tono condescendiente irritaba incluso a los que más lo querían y respetaban."},
    {"word":"contumaz","type":"adjective","gender":"","definition":"stubborn, obstinate, persistent in error or wrongdoing","example":"El acusado contumaz se negó a cooperar con la autoridad durante todo el proceso judicial."},
    {"word":"crispado","type":"adjective","gender":"","definition":"tense, irritated, on edge, wound up","example":"El ambiente estaba muy crispado desde que se conocieron los resultados de la votación."},
    {"word":"desabrido","type":"adjective","gender":"","definition":"tasteless, bland, surly, disagreeable in manner","example":"Le respondió de manera muy desabrida sin tener ningún motivo aparente para hacerlo."},
    {"word":"desapacible","type":"adjective","gender":"","definition":"unpleasant, disagreeable, harsh, rough","example":"El tiempo desapacible de noviembre impidió que se realizara el evento al aire libre."},
    {"word":"descarnado","type":"adjective","gender":"","definition":"stark, harsh, blunt, stripped of all softening","example":"Hizo una descripción descarnada de la realidad sin suavizar nada de lo que vio."},
    {"word":"desmesurado","type":"adjective","gender":"","definition":"excessive, disproportionate, immoderate","example":"Su ambición desmesurada lo llevó a tomar decisiones muy imprudentes para su empresa."},
    {"word":"díscolo","type":"adjective","gender":"","definition":"unruly, troublesome, rebellious, hard to manage","example":"Era el chamaco más díscolo del salón y el que más trabajo le daba a la maestra."},
    {"word":"dubitativo","type":"adjective","gender":"","definition":"doubtful, hesitant, uncertain, full of doubt","example":"Su respuesta dubitativa no convenció a nadie de los que estaban presentes ese día."},
    {"word":"escurridizo","type":"adjective","gender":"","definition":"slippery, elusive, hard to pin down or catch","example":"Era un testigo muy escurridizo que siempre encontraba la manera de evitar las preguntas."},
    {"word":"esquivo","type":"adjective","gender":"","definition":"elusive, aloof, shy, difficult to approach or engage","example":"Se mostró muy esquivo durante toda la entrevista sin comprometerse con ningún tema."},
    {"word":"huraño","type":"adjective","gender":"","definition":"unsociable, withdrawn, surly, avoiding company","example":"Se volvió muy huraño después del accidente y prácticamente dejó de salir de su casa."},
    {"word":"inquebrantable","type":"adjective","gender":"","definition":"unbreakable, unwavering, absolutely steadfast","example":"Mantuvo una fe inquebrantable en el proyecto a pesar de todos los tropiezos que tuvo."},
    {"word":"irascible","type":"adjective","gender":"","definition":"irascible, quick-tempered, easily angered","example":"Era tan irascible que cualquier contrariedad lo hacía explotar de coraje inmediatamente."},
    {"word":"liviano","type":"adjective","gender":"","definition":"light, slight, trivial, lacking substance or weight","example":"Sus argumentos eran muy livianos para sostener una tesis tan atrevida e importante."},
    {"word":"locuaz","type":"adjective","gender":"","definition":"talkative, loquacious, very voluble","example":"Era tan locuaz que a veces se le hacía difícil a uno encontrar el momento de hablar."},
    {"word":"mezquino","type":"adjective","gender":"","definition":"mean, petty, stingy, small-minded","example":"Su reacción mezquina ante el éxito ajeno decepcionó a todos los que lo estimaban."},
    {"word":"mordaz","type":"adjective","gender":"","definition":"biting, scathing, caustic, sharp-tongued","example":"Su crítica mordaz no dejó a nadie bien parado durante toda esa presentación."},
    {"word":"pendenciero","type":"adjective","gender":"","definition":"quarrelsome, belligerent, always looking for a fight","example":"Era un tipo muy pendenciero que buscaba pelea a la primera que podía siempre."},
    {"word":"propenso","type":"adjective","gender":"","definition":"prone to, inclined toward, susceptible to","example":"Era muy propenso a exagerar las cosas cuando se las contaba a sus cuates."},
    {"word":"pusilánime","type":"adjective","gender":"","definition":"faint-hearted, cowardly, lacking courage and resolve","example":"Una actitud pusilánime ante la injusticia no hace más que perpetuarla indefinidamente."},
    {"word":"rencoroso","type":"adjective","gender":"","definition":"resentful, bitter, unforgiving, harboring old grudges","example":"Era tan rencoroso que guardaba los agravios durante décadas enteras sin olvidar nada."},
    {"word":"reticente","type":"adjective","gender":"","definition":"reluctant, reticent, hesitant, holding back","example":"Se mostró muy reticente a hablar sobre su vida personal ante los reporteros."},
    {"word":"sombrío","type":"adjective","gender":"","definition":"gloomy, dark, somber, brooding and pessimistic","example":"Su visión sombría del futuro del país acabó por contagiar al resto de su equipo."},
    {"word":"suspicaz","type":"adjective","gender":"","definition":"suspicious, mistrustful, wary of others' intentions","example":"Era tan suspicaz que dudaba incluso de las buenas intenciones de sus propios amigos."},
    {"word":"tozudo","type":"adjective","gender":"","definition":"stubborn, pig-headed, refusing to change course","example":"Era tan tozudo que prefería fracasar antes que admitir que se había equivocado."},
    {"word":"turbio","type":"adjective","gender":"","definition":"murky, shady, cloudy, dubious and suspicious","example":"Sus negocios turbios acabaron llamando la atención de las autoridades fiscales."},
    {"word":"veleidoso","type":"adjective","gender":"","definition":"fickle, capricious, changeable without reason","example":"Su carácter veleidoso hacía imposible confiar en sus compromisos a largo plazo."},
    {"word":"voluble","type":"adjective","gender":"","definition":"changeable, fickle, moody, emotionally volatile","example":"Tan voluble era que nadie sabía con qué humor iba a llegar a trabajar cada día."},

    # ── ADVERBS ───────────────────────────────────────────────────────────────
    {"word":"a duras penas","type":"adverb","gender":"","definition":"barely, with great difficulty, by the skin of one's teeth","example":"A duras penas logró terminar el informe antes de que venciera el plazo final."},
    {"word":"a escondidas","type":"adverb","gender":"","definition":"secretly, on the sly, without anyone knowing","example":"Salió a escondidas para que nadie le preguntara a dónde iba ni con quién."},
    {"word":"a rajatabla","type":"adverb","gender":"","definition":"strictly, to the letter, without exceptions","example":"Cumplía el reglamento a rajatabla sin importarle las circunstancias particulares."},
    {"word":"a sabiendas","type":"adverb","gender":"","definition":"knowingly, deliberately, with full awareness of consequences","example":"Lo hizo a sabiendas de que iba a causar un problema serio con todos los demás."},
    {"word":"a trancas y barrancas","type":"adverb","gender":"","definition":"with great difficulty, by hook or by crook","example":"Salió adelante a trancas y barrancas pero al cabo lo logró con mucho esfuerzo."},
    {"word":"acaso","type":"adverb","gender":"","definition":"perhaps, maybe, by any chance","example":"Acaso tenga razón pero me cuesta trabajo aceptar sus argumentos sin más pruebas."},
    {"word":"adrede","type":"adverb","gender":"","definition":"on purpose, deliberately, intentionally","example":"Lo dijo adrede nomás para ver cómo reaccionaba ante semejante provocación."},
    {"word":"al cabo","type":"adverb","gender":"","definition":"in the end, after all, eventually","example":"Al cabo resultó que tenía razón en todo lo que había advertido desde el principio."},
    {"word":"al desgaire","type":"adverb","gender":"","definition":"carelessly, nonchalantly, with studied indifference","example":"Lo mencionó al desgaire como si la cosa no tuviera ninguna importancia para él."},
    {"word":"aun así","type":"adverb","gender":"","definition":"even so, nevertheless, still","example":"Aun así se negó a cambiar de postura a pesar de todas las evidencias en contra."},
    {"word":"apenas","type":"adverb","gender":"","definition":"barely, scarcely, hardly","example":"Apenas había dormido dos horas cuando ya sonó el despertador en la madrugada."},
    {"word":"aposta","type":"adverb","gender":"","definition":"on purpose, deliberately, with full intention","example":"Lo hizo aposta nomás para ver cómo reaccionaban todos ante esa situación."},
    {"word":"así y todo","type":"adverb","gender":"","definition":"even so, despite everything, all the same","example":"Así y todo decidió presentarse al examen aunque no hubiera estudiado casi nada."},
    {"word":"con creces","type":"adverb","gender":"","definition":"amply, more than enough, with interest","example":"Compensó con creces el error anterior con su desempeño en el siguiente proyecto."},
    {"word":"con miras a","type":"adverb","gender":"","definition":"with a view to, with the aim of","example":"Estudió inglés con miras a conseguir trabajo en una empresa trasnacional del norte."},
    {"word":"de buenas a primeras","type":"adverb","gender":"","definition":"all of a sudden, out of the blue, right off the bat","example":"De buenas a primeras anunció que se iba sin dar ninguna explicación a nadie."},
    {"word":"de mala gana","type":"adverb","gender":"","definition":"reluctantly, unwillingly, grudgingly","example":"Aceptó el encargo de mala gana pero al final lo cumplió con toda profesionalidad."},
    {"word":"de refilón","type":"adverb","gender":"","definition":"obliquely, in passing, glancingly, at an angle","example":"Le pegó de refilón pero fue suficiente para hacerle perder el equilibrio y caer."},
    {"word":"de sobra","type":"adverb","gender":"","definition":"more than enough, perfectly well, too well","example":"Sabe de sobra que ese comportamiento no es aceptable en ningún contexto laboral."},
    {"word":"de suyo","type":"adverb","gender":"","definition":"in itself, inherently, by its very nature","example":"El asunto es de suyo muy complejo sin necesidad de agregarle más complicaciones."},
    {"word":"en balde","type":"adverb","gender":"","definition":"in vain, to no avail, for nothing","example":"Esperó en balde durante horas a que alguien le devolviera la llamada ese día."},
    {"word":"en ciernes","type":"adverb","gender":"","definition":"in the making, budding, not yet fully developed","example":"El proyecto todavía estaba en ciernes cuando llegaron los primeros contratiempos."},
    {"word":"en demasía","type":"adverb","gender":"","definition":"excessively, too much, in excess","example":"Trabaja en demasía y eso está afectando seriamente su salud y su vida familiar."},
    {"word":"en entredicho","type":"adverb","gender":"","definition":"in doubt, in question, under suspicion","example":"Su honestidad quedó en entredicho una vez que se conocieron todos los hechos."},
    {"word":"en lontananza","type":"adverb","gender":"","definition":"in the distance, far off on the horizon","example":"Se veía en lontananza la silueta del volcán entre la neblina de la mañana fría."},
    {"word":"en resumidas cuentas","type":"adverb","gender":"","definition":"in short, in a nutshell, when all is said and done","example":"En resumidas cuentas el proyecto fue un fracaso que le costó mucho dinero a todos."},
    {"word":"en vano","type":"adverb","gender":"","definition":"in vain, uselessly, to no purpose","example":"Intentó en vano convencerlo de que reconsiderara su apresurada decisión de irse."},
    {"word":"entre bastidores","type":"adverb","gender":"","definition":"behind the scenes, away from the public eye","example":"Las verdaderas negociaciones ocurrían entre bastidores lejos de los medios de comunicación."},
    {"word":"mal que bien","type":"adverb","gender":"","definition":"somehow or other, after a fashion, more or less","example":"Mal que bien consiguieron un acuerdo que dejó a todos más o menos insatisfechos."},
    {"word":"nada más","type":"adverb","gender":"","definition":"as soon as, no sooner than; also: just, only (Mexican)","example":"Nada más entrar notó que algo no andaba bien en el ambiente de la oficina."},
    {"word":"ni mucho menos","type":"adverb","gender":"","definition":"far from it, not by a long shot, not even close","example":"No está conforme con los resultados ni mucho menos según lo que me platicó."},
    {"word":"por ende","type":"adverb","gender":"","definition":"therefore, consequently, hence","example":"No tenía la experiencia requerida y por ende no estaba listo para ese puesto."},
    {"word":"por si acaso","type":"adverb","gender":"","definition":"just in case, to be on the safe side","example":"Llévate el paraguas por si acaso aunque ahora no parezca que vaya a llover."},
    {"word":"sin ambages","type":"adverb","gender":"","definition":"without beating about the bush, straight to the point","example":"Dijo sin ambages lo que pensaba aunque a nadie le fuera a gustar escucharlo."},
    {"word":"sin más ni más","type":"adverb","gender":"","definition":"just like that, without warning or reason","example":"Se paró y se fue sin más ni más dejando a todos con la palabra en la boca."},
    {"word":"siquiera","type":"adverb","gender":"","definition":"at least, even; ni siquiera — not even","example":"Ni siquiera se molestó en mandar un mensajito para avisar que no iba a llegar."},
    {"word":"sobremanera","type":"adverb","gender":"","definition":"exceedingly, enormously, beyond measure","example":"Le afectó sobremanera la crítica porque venía de alguien a quien respetaba mucho."},
    {"word":"todavía más","type":"adverb","gender":"","definition":"even more, still more, increasingly","example":"Lo que vino después fue todavía más sorprendente de lo que cualquiera había esperado."},
]
