DECK = [
    # ── NOUNS ──────────────────────────────────────────────────────────────────
    {"word":"el ambiente","type":"noun","gender":"masculine","definition":"atmosphere, environment","example":"El ambiente del restaurante era muy acogedor y tranquilo."},
    {"word":"el apoyo","type":"noun","gender":"masculine","definition":"support, backing","example":"Contaba con el apoyo incondicional de su familia en todo momento."},
    {"word":"el argumento","type":"noun","gender":"masculine","definition":"argument, plot","example":"El argumento de la novela me pareció muy original e interesante."},
    {"word":"el asunto","type":"noun","gender":"masculine","definition":"matter, issue, affair","example":"Tenemos que hablar de un asunto importante antes de la reunión."},
    {"word":"el aumento","type":"noun","gender":"masculine","definition":"increase, raise","example":"Los empleados pidieron un aumento de sueldo al director."},
    {"word":"el bienestar","type":"noun","gender":"masculine","definition":"wellbeing, welfare","example":"El bienestar de los ciudadanos es la prioridad del gobierno."},
    {"word":"el cambio","type":"noun","gender":"masculine","definition":"change, exchange","example":"El cambio climático es uno de los mayores desafíos de nuestra era."},
    {"word":"el cargo","type":"noun","gender":"masculine","definition":"position, charge, post","example":"Fue nombrado para el cargo de director general de la empresa."},
    {"word":"el compromiso","type":"noun","gender":"masculine","definition":"commitment, compromise","example":"Firmaron un compromiso para mejorar las condiciones laborales."},
    {"word":"el conflicto","type":"noun","gender":"masculine","definition":"conflict, dispute","example":"El conflicto entre los dos países duró más de una década."},
    {"word":"el conocimiento","type":"noun","gender":"masculine","definition":"knowledge, awareness","example":"El conocimiento del idioma local facilita la integración cultural."},
    {"word":"el conjunto","type":"noun","gender":"masculine","definition":"set, group, whole","example":"El conjunto de medidas propuestas mejoraría la economía."},
    {"word":"el consumo","type":"noun","gender":"masculine","definition":"consumption, use","example":"El consumo de energía renovable ha aumentado significativamente."},
    {"word":"el control","type":"noun","gender":"masculine","definition":"control, check","example":"El gobierno perdió el control de la situación económica."},
    {"word":"el criterio","type":"noun","gender":"masculine","definition":"criterion, judgment","example":"El criterio de selección para el puesto era la experiencia previa."},
    {"word":"el dato","type":"noun","gender":"masculine","definition":"fact, piece of data","example":"Los datos muestran que la situación ha mejorado este año."},
    {"word":"el debate","type":"noun","gender":"masculine","definition":"debate, discussion","example":"El debate político duró más de tres horas en el congreso."},
    {"word":"el desarrollo","type":"noun","gender":"masculine","definition":"development, growth","example":"El desarrollo sostenible es fundamental para el futuro del planeta."},
    {"word":"el desafío","type":"noun","gender":"masculine","definition":"challenge, dare","example":"Superar ese desafío requirió meses de esfuerzo y dedicación."},
    {"word":"el discurso","type":"noun","gender":"masculine","definition":"speech, discourse","example":"El presidente pronunció un discurso ante miles de ciudadanos."},
    {"word":"el esfuerzo","type":"noun","gender":"masculine","definition":"effort, exertion","example":"Con mucho esfuerzo logró terminar la carrera universitaria."},
    {"word":"el estado","type":"noun","gender":"masculine","definition":"state, condition","example":"El estado de la carretera era peligroso tras las lluvias."},
    {"word":"el éxito","type":"noun","gender":"masculine","definition":"success, hit","example":"El éxito de la película superó todas las expectativas del estudio."},
    {"word":"el factor","type":"noun","gender":"masculine","definition":"factor, element","example":"El factor climático influyó mucho en la producción agrícola."},
    {"word":"el fenómeno","type":"noun","gender":"masculine","definition":"phenomenon","example":"El fenómeno de la migración masiva preocupa a muchos países."},
    {"word":"el fondo","type":"noun","gender":"masculine","definition":"background, bottom, fund","example":"En el fondo, todos sabían que la decisión era incorrecta."},
    {"word":"el funcionamiento","type":"noun","gender":"masculine","definition":"functioning, operation","example":"El funcionamiento del nuevo sistema es mucho más eficiente."},
    {"word":"el fundamento","type":"noun","gender":"masculine","definition":"foundation, basis","example":"El respeto mutuo es el fundamento de cualquier relación sana."},
    {"word":"el impacto","type":"noun","gender":"masculine","definition":"impact, effect","example":"El impacto de la crisis económica se notó en todos los sectores."},
    {"word":"el índice","type":"noun","gender":"masculine","definition":"index, rate, indicator","example":"El índice de desempleo bajó un dos por ciento este trimestre."},
    {"word":"el informe","type":"noun","gender":"masculine","definition":"report, statement","example":"El informe anual reveló graves irregularidades en las cuentas."},
    {"word":"el interés","type":"noun","gender":"masculine","definition":"interest, concern","example":"Mostró gran interés por aprender idiomas desde pequeño."},
    {"word":"el logro","type":"noun","gender":"masculine","definition":"achievement, accomplishment","example":"Ganar el campeonato fue el mayor logro de su carrera deportiva."},
    {"word":"el marco","type":"noun","gender":"masculine","definition":"frame, framework, context","example":"El acuerdo se firmó en el marco de las negociaciones de paz."},
    {"word":"el medio","type":"noun","gender":"masculine","definition":"means, medium, environment","example":"Los medios de comunicación tienen gran influencia en la opinión pública."},
    {"word":"el mecanismo","type":"noun","gender":"masculine","definition":"mechanism, device","example":"El mecanismo de defensa del sistema inmune es muy complejo."},
    {"word":"el mensaje","type":"noun","gender":"masculine","definition":"message","example":"El mensaje que quería transmitir llegó claramente al público."},
    {"word":"el método","type":"noun","gender":"masculine","definition":"method, approach","example":"El método científico requiere observación, hipótesis y experimentación."},
    {"word":"el modelo","type":"noun","gender":"masculine","definition":"model, pattern, example","example":"Este edificio es un modelo de arquitectura sostenible moderna."},
    {"word":"el nivel","type":"noun","gender":"masculine","definition":"level, standard","example":"El nivel de vida ha mejorado considerablemente en los últimos años."},
    {"word":"el objetivo","type":"noun","gender":"masculine","definition":"objective, goal, target","example":"Su objetivo principal era terminar el proyecto antes de diciembre."},
    {"word":"el obstáculo","type":"noun","gender":"masculine","definition":"obstacle, barrier","example":"La falta de financiación fue el principal obstáculo del proyecto."},
    {"word":"el papel","type":"noun","gender":"masculine","definition":"role, paper","example":"El papel de la educación en el desarrollo social es fundamental."},
    {"word":"el plazo","type":"noun","gender":"masculine","definition":"deadline, term, period","example":"Hay que entregar el informe dentro del plazo establecido."},
    {"word":"el planteamiento","type":"noun","gender":"masculine","definition":"approach, proposal, framing","example":"El planteamiento del problema era demasiado complejo para resolverlo rápido."},
    {"word":"el poder","type":"noun","gender":"masculine","definition":"power, authority","example":"El poder ejecutivo y legislativo deben estar claramente separados."},
    {"word":"el proceso","type":"noun","gender":"masculine","definition":"process, procedure","example":"El proceso de selección de candidatos duró varios meses."},
    {"word":"el propósito","type":"noun","gender":"masculine","definition":"purpose, intention","example":"El propósito de la reunión era encontrar una solución definitiva."},
    {"word":"el recurso","type":"noun","gender":"masculine","definition":"resource, means","example":"Los recursos naturales del país son su mayor riqueza económica."},
    {"word":"el reto","type":"noun","gender":"masculine","definition":"challenge, dare","example":"Aprender un nuevo idioma a los cincuenta años es un gran reto."},
    {"word":"el riesgo","type":"noun","gender":"masculine","definition":"risk, danger","example":"Asumir ese riesgo podría traer grandes beneficios a largo plazo."},
    {"word":"el rol","type":"noun","gender":"masculine","definition":"role, part","example":"El rol de los padres en la educación de los hijos es esencial."},
    {"word":"el rumbo","type":"noun","gender":"masculine","definition":"direction, course, heading","example":"La empresa cambió de rumbo tras la llegada del nuevo director."},
    {"word":"el sector","type":"noun","gender":"masculine","definition":"sector, area, field","example":"El sector tecnológico creció un quince por ciento el año pasado."},
    {"word":"el seguimiento","type":"noun","gender":"masculine","definition":"monitoring, follow-up","example":"El seguimiento del paciente después de la operación fue riguroso."},
    {"word":"el sistema","type":"noun","gender":"masculine","definition":"system","example":"El sistema educativo necesita reformas profundas para mejorar su calidad."},
    {"word":"el surgimiento","type":"noun","gender":"masculine","definition":"emergence, rise","example":"El surgimiento de nuevas tecnologías transformó la industria manufacturera."},
    {"word":"el tejido","type":"noun","gender":"masculine","definition":"fabric, tissue, network","example":"El tejido social del barrio se fortaleció con actividades comunitarias."},
    {"word":"el término","type":"noun","gender":"masculine","definition":"term, end, word","example":"En términos generales, el proyecto fue un éxito rotundo."},
    {"word":"el trasfondo","type":"noun","gender":"masculine","definition":"background, underlying issue","example":"El trasfondo político de la decisión era evidente para todos."},
    {"word":"el vínculo","type":"noun","gender":"masculine","definition":"bond, link, tie","example":"El vínculo entre madre e hijo es uno de los más fuertes."},
    {"word":"la actuación","type":"noun","gender":"feminine","definition":"performance, action","example":"La actuación de la actriz principal fue brillante en toda la obra."},
    {"word":"la amenaza","type":"noun","gender":"feminine","definition":"threat, menace","example":"La amenaza del cambio climático requiere acción internacional urgente."},
    {"word":"la brecha","type":"noun","gender":"feminine","definition":"gap, breach, divide","example":"La brecha digital entre generaciones sigue siendo un problema importante."},
    {"word":"la capacidad","type":"noun","gender":"feminine","definition":"capacity, ability","example":"Su capacidad para resolver problemas complejos impresionó a todos."},
    {"word":"la causa","type":"noun","gender":"feminine","definition":"cause, reason","example":"La causa principal del accidente fue la falta de visibilidad."},
    {"word":"la cifra","type":"noun","gender":"feminine","definition":"figure, number, digit","example":"Las cifras de desempleo publicadas hoy son preocupantes."},
    {"word":"la circunstancia","type":"noun","gender":"feminine","definition":"circumstance, situation","example":"Las circunstancias del caso hacían difícil tomar una decisión rápida."},
    {"word":"la clave","type":"noun","gender":"feminine","definition":"key, clue","example":"La comunicación honesta es la clave de cualquier relación exitosa."},
    {"word":"la cobertura","type":"noun","gender":"feminine","definition":"coverage, coverage area","example":"La cobertura de internet en zonas rurales sigue siendo insuficiente."},
    {"word":"la conciencia","type":"noun","gender":"feminine","definition":"consciousness, awareness","example":"La conciencia ambiental ha crecido mucho entre los jóvenes."},
    {"word":"la consecuencia","type":"noun","gender":"feminine","definition":"consequence, result","example":"Las consecuencias de ignorar el problema fueron muy graves."},
    {"word":"la crisis","type":"noun","gender":"feminine","definition":"crisis, turning point","example":"La crisis económica afectó gravemente a millones de familias."},
    {"word":"la demanda","type":"noun","gender":"feminine","definition":"demand, request, lawsuit","example":"La demanda de productos orgánicos ha aumentado considerablemente."},
    {"word":"la desigualdad","type":"noun","gender":"feminine","definition":"inequality, disparity","example":"La desigualdad social es uno de los problemas más graves del país."},
    {"word":"la dificultad","type":"noun","gender":"feminine","definition":"difficulty, hardship","example":"Superaron las dificultades iniciales con mucho trabajo y perseverancia."},
    {"word":"la diversidad","type":"noun","gender":"feminine","definition":"diversity, variety","example":"La diversidad cultural de la ciudad la hace especialmente atractiva."},
    {"word":"la eficiencia","type":"noun","gender":"feminine","definition":"efficiency, effectiveness","example":"La eficiencia energética de los nuevos edificios es mucho mayor."},
    {"word":"la elaboración","type":"noun","gender":"feminine","definition":"preparation, development, elaboration","example":"La elaboración del informe llevó más tiempo del esperado."},
    {"word":"la escasez","type":"noun","gender":"feminine","definition":"scarcity, shortage","example":"La escasez de agua potable es un problema global urgente."},
    {"word":"la estabilidad","type":"noun","gender":"feminine","definition":"stability, steadiness","example":"La estabilidad política del país atrajo inversiones extranjeras."},
    {"word":"la estrategia","type":"noun","gender":"feminine","definition":"strategy, plan","example":"La estrategia de marketing de la empresa resultó muy efectiva."},
    {"word":"la estructura","type":"noun","gender":"feminine","definition":"structure, framework","example":"La estructura del texto facilita la comprensión de las ideas."},
    {"word":"la evidencia","type":"noun","gender":"feminine","definition":"evidence, proof","example":"La evidencia científica apoya claramente esta teoría sobre el clima."},
    {"word":"la formación","type":"noun","gender":"feminine","definition":"training, education, formation","example":"La formación continua es esencial en el mundo laboral actual."},
    {"word":"la fortaleza","type":"noun","gender":"feminine","definition":"strength, fortress","example":"Su mayor fortaleza era la capacidad de mantenerse tranquilo bajo presión."},
    {"word":"la fuente","type":"noun","gender":"feminine","definition":"source, fountain","example":"Es importante verificar la fuente de la información antes de compartirla."},
    {"word":"la gestión","type":"noun","gender":"feminine","definition":"management, administration","example":"La gestión eficiente de los recursos es clave para el éxito."},
    {"word":"la globalización","type":"noun","gender":"feminine","definition":"globalization","example":"La globalización ha transformado las economías de todo el mundo."},
    {"word":"la identidad","type":"noun","gender":"feminine","definition":"identity","example":"Preservar la identidad cultural es importante en un mundo globalizado."},
    {"word":"la imagen","type":"noun","gender":"feminine","definition":"image, picture","example":"La imagen de la empresa mejoró tras la campaña de responsabilidad social."},
    {"word":"la incertidumbre","type":"noun","gender":"feminine","definition":"uncertainty, doubt","example":"La incertidumbre económica está afectando las decisiones de inversión."},
    {"word":"la influencia","type":"noun","gender":"feminine","definition":"influence, effect","example":"La influencia de la cultura americana es visible en todo el mundo."},
    {"word":"la iniciativa","type":"noun","gender":"feminine","definition":"initiative, drive","example":"La iniciativa privada puede complementar los servicios públicos."},
    {"word":"la innovación","type":"noun","gender":"feminine","definition":"innovation, novelty","example":"La innovación tecnológica está transformando todos los sectores económicos."},
    {"word":"la inversión","type":"noun","gender":"feminine","definition":"investment","example":"La inversión en educación es fundamental para el desarrollo del país."},
    {"word":"la mayoría","type":"noun","gender":"feminine","definition":"majority, most","example":"La mayoría de los encuestados apoyó la nueva propuesta legislativa."},
    {"word":"la medida","type":"noun","gender":"feminine","definition":"measure, step, size","example":"Las medidas adoptadas por el gobierno lograron reducir la inflación."},
    {"word":"la minoría","type":"noun","gender":"feminine","definition":"minority","example":"Es fundamental proteger los derechos de cualquier minoría étnica."},
    {"word":"la normativa","type":"noun","gender":"feminine","definition":"regulations, rules","example":"La normativa europea sobre privacidad es muy estricta y detallada."},
    {"word":"la perspectiva","type":"noun","gender":"feminine","definition":"perspective, outlook","example":"Es importante analizar el problema desde diferentes perspectivas."},
    {"word":"la política","type":"noun","gender":"feminine","definition":"policy, politics","example":"La política fiscal del gobierno busca reducir el déficit público."},
    {"word":"la presión","type":"noun","gender":"feminine","definition":"pressure, stress","example":"La presión laboral excesiva puede provocar serios problemas de salud."},
    {"word":"la propuesta","type":"noun","gender":"feminine","definition":"proposal, suggestion","example":"La propuesta del comité fue aprobada por unanimidad en la asamblea."},
    {"word":"la realidad","type":"noun","gender":"feminine","definition":"reality, fact","example":"La realidad económica del país es más compleja de lo que parece."},
    {"word":"la red","type":"noun","gender":"feminine","definition":"network, net","example":"La red de transporte público de la ciudad es muy eficiente."},
    {"word":"la reforma","type":"noun","gender":"feminine","definition":"reform, renovation","example":"La reforma educativa propuesta generó mucho debate en el parlamento."},
    {"word":"la responsabilidad","type":"noun","gender":"feminine","definition":"responsibility, liability","example":"Asumir la responsabilidad de los propios errores es señal de madurez."},
    {"word":"la seguridad","type":"noun","gender":"feminine","definition":"security, safety, certainty","example":"La seguridad ciudadana mejoró gracias a las nuevas medidas policiales."},
    {"word":"la tendencia","type":"noun","gender":"feminine","definition":"tendency, trend","example":"La tendencia actual es consumir productos más sostenibles y ecológicos."},
    {"word":"la transparencia","type":"noun","gender":"feminine","definition":"transparency","example":"La transparencia en la gestión pública genera confianza en los ciudadanos."},
    {"word":"la vivienda","type":"noun","gender":"feminine","definition":"housing, dwelling","example":"El acceso a una vivienda digna es un derecho fundamental de todos."},
    {"word":"la voluntad","type":"noun","gender":"feminine","definition":"will, willingness","example":"Sin voluntad política, ninguna reforma puede llevarse a cabo."},

    # ── VERBS ──────────────────────────────────────────────────────────────────
    {"word":"abarcar","type":"verb","gender":"","definition":"to cover, encompass, span","example":"El proyecto abarca varias disciplinas científicas y humanísticas."},
    {"word":"abordar","type":"verb","gender":"","definition":"to tackle, address, board","example":"Es necesario abordar el problema desde una perspectiva integral."},
    {"word":"acoger","type":"verb","gender":"","definition":"to welcome, receive, shelter","example":"La ciudad acogió a miles de refugiados durante el conflicto."},
    {"word":"acontecer","type":"verb","gender":"","definition":"to happen, occur, take place","example":"Los cambios que acontecieron durante ese período fueron históricos."},
    {"word":"adaptar","type":"verb","gender":"","definition":"to adapt, adjust","example":"Tuvieron que adaptar el plan a las nuevas circunstancias del mercado."},
    {"word":"afrontar","type":"verb","gender":"","definition":"to face, confront, tackle","example":"Es importante afrontar los problemas en lugar de ignorarlos."},
    {"word":"agotar","type":"verb","gender":"","definition":"to exhaust, deplete, wear out","example":"Las negociaciones se agotaron sin llegar a ningún acuerdo definitivo."},
    {"word":"alcanzar","type":"verb","gender":"","definition":"to reach, achieve, attain","example":"Finalmente alcanzaron el acuerdo después de meses de negociaciones."},
    {"word":"ampliar","type":"verb","gender":"","definition":"to expand, enlarge, extend","example":"La empresa decidió ampliar sus operaciones a nuevos mercados internacionales."},
    {"word":"analizar","type":"verb","gender":"","definition":"to analyze, examine","example":"Hay que analizar cuidadosamente los datos antes de sacar conclusiones."},
    {"word":"apostar","type":"verb","gender":"","definition":"to bet, wager, commit to","example":"El gobierno apostó por las energías renovables como solución energética."},
    {"word":"apoyar","type":"verb","gender":"","definition":"to support, back, lean on","example":"Sus compañeros le apoyaron durante los momentos más difíciles."},
    {"word":"aprovechar","type":"verb","gender":"","definition":"to take advantage of, make use of","example":"Debes aprovechar esta oportunidad única para mejorar tu formación."},
    {"word":"asumir","type":"verb","gender":"","definition":"to assume, take on, accept","example":"Decidió asumir la responsabilidad del fracaso sin culpar a otros."},
    {"word":"avanzar","type":"verb","gender":"","definition":"to advance, progress, move forward","example":"El proyecto avanzó más rápido de lo previsto gracias al equipo."},
    {"word":"carecer","type":"verb","gender":"","definition":"to lack, be without","example":"El sistema educativo carece de los recursos necesarios para funcionar bien."},
    {"word":"ceder","type":"verb","gender":"","definition":"to yield, give in, transfer","example":"Ninguna de las partes quería ceder en sus posiciones iniciales."},
    {"word":"comprometer","type":"verb","gender":"","definition":"to commit, compromise, endanger","example":"Se comprometió a entregar el informe antes del final de la semana."},
    {"word":"concretar","type":"verb","gender":"","definition":"to specify, finalize, make concrete","example":"Necesitamos concretar los detalles del acuerdo antes de firmarlo."},
    {"word":"conllevar","type":"verb","gender":"","definition":"to entail, involve, carry","example":"Ese puesto conlleva una gran responsabilidad y mucha dedicación diaria."},
    {"word":"consolidar","type":"verb","gender":"","definition":"to consolidate, strengthen","example":"La empresa logró consolidar su posición en el mercado europeo."},
    {"word":"contemplar","type":"verb","gender":"","definition":"to contemplate, consider, gaze at","example":"La propuesta contempla medidas para reducir la pobreza en zonas rurales."},
    {"word":"contrastar","type":"verb","gender":"","definition":"to contrast, compare, verify","example":"Es útil contrastar diferentes fuentes antes de tomar una decisión."},
    {"word":"contribuir","type":"verb","gender":"","definition":"to contribute, add to","example":"Cada ciudadano puede contribuir al bienestar de su comunidad."},
    {"word":"cuestionar","type":"verb","gender":"","definition":"to question, challenge","example":"Los estudiantes aprendieron a cuestionar las ideas establecidas con rigor."},
    {"word":"debatir","type":"verb","gender":"","definition":"to debate, discuss","example":"Los parlamentarios debatieron la propuesta durante más de cinco horas."},
    {"word":"destacar","type":"verb","gender":"","definition":"to stand out, highlight, emphasize","example":"Su trabajo destacó por su originalidad y rigor metodológico."},
    {"word":"determinar","type":"verb","gender":"","definition":"to determine, decide","example":"Los expertos intentaron determinar la causa exacta del accidente."},
    {"word":"disminuir","type":"verb","gender":"","definition":"to decrease, reduce, diminish","example":"El uso de energías renovables ayuda a disminuir las emisiones de CO2."},
    {"word":"elaborar","type":"verb","gender":"","definition":"to develop, prepare, elaborate","example":"El equipo tardó semanas en elaborar el informe final del proyecto."},
    {"word":"emprender","type":"verb","gender":"","definition":"to undertake, begin, start","example":"Decidió emprender un viaje de varios meses por América Latina."},
    {"word":"enfrentar","type":"verb","gender":"","definition":"to face, confront","example":"El país debe enfrentar los desafíos del cambio climático sin demora."},
    {"word":"establecer","type":"verb","gender":"","definition":"to establish, set up, lay down","example":"El acuerdo estableció nuevas normas para el comercio bilateral."},
    {"word":"evaluar","type":"verb","gender":"","definition":"to evaluate, assess","example":"Es necesario evaluar los resultados antes de continuar con el proyecto."},
    {"word":"fomentar","type":"verb","gender":"","definition":"to promote, encourage, foster","example":"El gobierno quiere fomentar el uso del transporte público entre ciudadanos."},
    {"word":"fortalecer","type":"verb","gender":"","definition":"to strengthen, reinforce","example":"El deporte regular ayuda a fortalecer tanto el cuerpo como la mente."},
    {"word":"garantizar","type":"verb","gender":"","definition":"to guarantee, ensure","example":"El contrato garantiza las condiciones laborales mínimas para todos."},
    {"word":"generar","type":"verb","gender":"","definition":"to generate, create, produce","example":"La nueva planta solar generará energía para miles de hogares."},
    {"word":"gestionar","type":"verb","gender":"","definition":"to manage, handle, administer","example":"Aprendió a gestionar su tiempo de manera más eficiente y productiva."},
    {"word":"identificar","type":"verb","gender":"","definition":"to identify, recognize","example":"Es fundamental identificar las causas reales del problema para solucionarlo."},
    {"word":"implementar","type":"verb","gender":"","definition":"to implement, put into practice","example":"El equipo tardó meses en implementar el nuevo sistema informático."},
    {"word":"impulsar","type":"verb","gender":"","definition":"to drive, promote, boost","example":"Las nuevas políticas buscan impulsar el crecimiento económico del país."},
    {"word":"incidir","type":"verb","gender":"","definition":"to influence, affect, have an impact","example":"La educación temprana incide directamente en el desarrollo del niño."},
    {"word":"incorporar","type":"verb","gender":"","definition":"to incorporate, include, join","example":"El texto incorpora las últimas investigaciones sobre el tema."},
    {"word":"integrar","type":"verb","gender":"","definition":"to integrate, include, make up","example":"El programa intenta integrar a los inmigrantes en la sociedad."},
    {"word":"intervenir","type":"verb","gender":"","definition":"to intervene, take part, operate","example":"El mediador tuvo que intervenir para calmar el conflicto."},
    {"word":"llevar a cabo","type":"verb","gender":"","definition":"to carry out, accomplish","example":"Lograron llevar a cabo el proyecto dentro del presupuesto previsto."},
    {"word":"mantener","type":"verb","gender":"","definition":"to maintain, keep, sustain","example":"Es difícil mantener el equilibrio entre trabajo y vida personal."},
    {"word":"mejorar","type":"verb","gender":"","definition":"to improve, get better","example":"La situación económica mejoró notablemente durante el último trimestre."},
    {"word":"obtener","type":"verb","gender":"","definition":"to obtain, get, achieve","example":"Obtuvo los mejores resultados de su clase en los exámenes finales."},
    {"word":"plantear","type":"verb","gender":"","definition":"to raise, put forward, pose","example":"El investigador planteó una hipótesis revolucionaria sobre el origen del universo."},
    {"word":"potenciar","type":"verb","gender":"","definition":"to enhance, strengthen, boost","example":"El programa busca potenciar las habilidades creativas de los estudiantes."},
    {"word":"profundizar","type":"verb","gender":"","definition":"to deepen, go deeper into","example":"Necesitamos profundizar en el análisis antes de tomar decisiones."},
    {"word":"promover","type":"verb","gender":"","definition":"to promote, encourage, advance","example":"La organización trabaja para promover los derechos humanos en todo el mundo."},
    {"word":"proponer","type":"verb","gender":"","definition":"to propose, suggest","example":"El comité propuso varias medidas para reducir la contaminación urbana."},
    {"word":"reducir","type":"verb","gender":"","definition":"to reduce, cut down, decrease","example":"La empresa logró reducir sus emisiones de carbono en un treinta por ciento."},
    {"word":"reflejar","type":"verb","gender":"","definition":"to reflect, show, mirror","example":"Los resultados reflejan el esfuerzo realizado por todo el equipo."},
    {"word":"requerir","type":"verb","gender":"","definition":"to require, need, demand","example":"Este trabajo requiere una gran concentración y atención al detalle."},
    {"word":"resolver","type":"verb","gender":"","definition":"to solve, resolve, settle","example":"Finalmente lograron resolver el conflicto a través del diálogo."},
    {"word":"señalar","type":"verb","gender":"","definition":"to point out, indicate, note","example":"El informe señala varios problemas graves en el sistema sanitario."},
    {"word":"superar","type":"verb","gender":"","definition":"to overcome, surpass, exceed","example":"Superó todos los obstáculos con determinación y trabajo constante."},
    {"word":"surgir","type":"verb","gender":"","definition":"to arise, emerge, come up","example":"Surgieron varios problemas inesperados durante la implementación del plan."},
    {"word":"tender","type":"verb","gender":"","definition":"to tend, lean towards","example":"Las temperaturas tienden a subir durante los meses de verano."},
    {"word":"transformar","type":"verb","gender":"","definition":"to transform, change","example":"La revolución digital transformó completamente la industria editorial."},
    {"word":"valorar","type":"verb","gender":"","definition":"to value, assess, appreciate","example":"Es importante valorar el trabajo de quienes nos rodean cada día."},
    {"word":"vincular","type":"verb","gender":"","definition":"to link, connect, tie","example":"El estudio vincula el estrés laboral con problemas cardiovasculares graves."},

    # ── ADJECTIVES ────────────────────────────────────────────────────────────
    {"word":"adecuado","type":"adjective","gender":"","definition":"adequate, suitable, appropriate","example":"Es adecuado revisar el contrato antes de firmarlo definitivamente."},
    {"word":"agotador","type":"adjective","gender":"","definition":"exhausting, draining","example":"El maratón fue agotador pero la satisfacción al terminar fue enorme."},
    {"word":"ambiguo","type":"adjective","gender":"","definition":"ambiguous, unclear","example":"La respuesta del director fue ambigua y no aclaró nada concreto."},
    {"word":"amplio","type":"adjective","gender":"","definition":"wide, broad, ample","example":"Tiene una amplia experiencia en el campo de la inteligencia artificial."},
    {"word":"arriesgado","type":"adjective","gender":"","definition":"risky, daring","example":"Invertir todos los ahorros en una sola empresa es muy arriesgado."},
    {"word":"brillante","type":"adjective","gender":"","definition":"brilliant, bright, outstanding","example":"Su actuación fue tan brillante que recibió una ovación de pie."},
    {"word":"clave","type":"adjective","gender":"","definition":"key, crucial","example":"La comunicación efectiva es un factor clave en cualquier equipo."},
    {"word":"complejo","type":"adjective","gender":"","definition":"complex, complicated","example":"El problema es más complejo de lo que parecía en un principio."},
    {"word":"comprometido","type":"adjective","gender":"","definition":"committed, dedicated, involved","example":"Es una persona muy comprometida con las causas sociales y ambientales."},
    {"word":"considerable","type":"adjective","gender":"","definition":"considerable, significant","example":"El aumento en las ventas fue considerable durante el último trimestre."},
    {"word":"constante","type":"adjective","gender":"","definition":"constant, steady, persistent","example":"El esfuerzo constante es la clave del éxito a largo plazo."},
    {"word":"contradictorio","type":"adjective","gender":"","definition":"contradictory, inconsistent","example":"Sus declaraciones resultaron contradictorias y generaron mucha confusión."},
    {"word":"conveniente","type":"adjective","gender":"","definition":"convenient, suitable, advisable","example":"No es conveniente tomar decisiones importantes cuando se está cansado."},
    {"word":"crítico","type":"adjective","gender":"","definition":"critical, crucial, critical-minded","example":"El período crítico de la negociación duró tres días intensos."},
    {"word":"crucial","type":"adjective","gender":"","definition":"crucial, decisive","example":"Este momento es crucial para el futuro de la empresa y sus empleados."},
    {"word":"decidido","type":"adjective","gender":"","definition":"determined, resolute, decisive","example":"Es una persona muy decidida que nunca duda ante los obstáculos."},
    {"word":"definitivo","type":"adjective","gender":"","definition":"definitive, final, conclusive","example":"La decisión definitiva se tomará después de analizar todos los datos."},
    {"word":"delicado","type":"adjective","gender":"","definition":"delicate, sensitive, fragile","example":"Este es un asunto muy delicado que debe tratarse con mucho cuidado."},
    {"word":"destacado","type":"adjective","gender":"","definition":"outstanding, notable, prominent","example":"Es un científico destacado reconocido a nivel internacional por su trabajo."},
    {"word":"determinado","type":"adjective","gender":"","definition":"determined, certain, specific","example":"Solo en determinadas circunstancias se puede hacer una excepción."},
    {"word":"eficaz","type":"adjective","gender":"","definition":"effective, efficient","example":"El nuevo tratamiento resultó ser muy eficaz contra la enfermedad."},
    {"word":"eficiente","type":"adjective","gender":"","definition":"efficient, productive","example":"Un sistema de transporte eficiente reduce la contaminación urbana."},
    {"word":"equilibrado","type":"adjective","gender":"","definition":"balanced, well-balanced","example":"Una dieta equilibrada es esencial para mantener una buena salud."},
    {"word":"escaso","type":"adjective","gender":"","definition":"scarce, limited, insufficient","example":"Los recursos son escasos y deben distribuirse de manera equitativa."},
    {"word":"específico","type":"adjective","gender":"","definition":"specific, particular","example":"Necesito información más específica para tomar una decisión correcta."},
    {"word":"estricto","type":"adjective","gender":"","definition":"strict, rigorous","example":"El reglamento es muy estricto sobre el uso de dispositivos electrónicos."},
    {"word":"evidente","type":"adjective","gender":"","definition":"evident, obvious, clear","example":"Era evidente que el proyecto necesitaba más tiempo para completarse."},
    {"word":"exhaustivo","type":"adjective","gender":"","definition":"exhaustive, thorough, comprehensive","example":"El análisis exhaustivo del caso tardó varias semanas en completarse."},
    {"word":"flexible","type":"adjective","gender":"","definition":"flexible, adaptable","example":"El horario flexible permite a los empleados conciliar trabajo y familia."},
    {"word":"fundamental","type":"adjective","gender":"","definition":"fundamental, essential, basic","example":"El respeto mutuo es fundamental para que funcione cualquier relación."},
    {"word":"grave","type":"adjective","gender":"","definition":"serious, grave, severe","example":"La situación económica es grave y requiere medidas urgentes e inmediatas."},
    {"word":"innovador","type":"adjective","gender":"","definition":"innovative, groundbreaking","example":"Su enfoque innovador resolvió el problema de manera completamente inesperada."},
    {"word":"integral","type":"adjective","gender":"","definition":"comprehensive, integral, whole","example":"Propusieron un plan integral para mejorar la calidad del sistema educativo."},
    {"word":"intenso","type":"adjective","gender":"","definition":"intense, deep, strong","example":"Vivieron una experiencia muy intensa durante su viaje por el desierto."},
    {"word":"notable","type":"adjective","gender":"","definition":"notable, remarkable, outstanding","example":"Hubo un avance notable en las negociaciones durante la última sesión."},
    {"word":"novedoso","type":"adjective","gender":"","definition":"novel, new, innovative","example":"El diseño novedoso del producto llamó la atención de los consumidores."},
    {"word":"óptimo","type":"adjective","gender":"","definition":"optimal, best, ideal","example":"Las condiciones óptimas para el cultivo se dan en primavera."},
    {"word":"polémico","type":"adjective","gender":"","definition":"controversial, contentious","example":"La propuesta fue muy polémica y generó un intenso debate público."},
    {"word":"preciso","type":"adjective","gender":"","definition":"precise, exact, necessary","example":"Es preciso actuar con rapidez para evitar consecuencias peores."},
    {"word":"prioritario","type":"adjective","gender":"","definition":"priority, top-priority","example":"La reducción del déficit es un objetivo prioritario para el gobierno."},
    {"word":"progresivo","type":"adjective","gender":"","definition":"progressive, gradual","example":"El deterioro progresivo de su salud preocupó a toda la familia."},
    {"word":"prominente","type":"adjective","gender":"","definition":"prominent, leading, eminent","example":"Es una figura prominente en el mundo de la política internacional."},
    {"word":"relevante","type":"adjective","gender":"","definition":"relevant, important, significant","example":"Es importante incluir solo la información más relevante en el informe."},
    {"word":"riguroso","type":"adjective","gender":"","definition":"rigorous, thorough, strict","example":"El proceso de selección fue muy riguroso para garantizar la calidad."},
    {"word":"significativo","type":"adjective","gender":"","definition":"significant, meaningful","example":"Hubo un cambio significativo en la actitud de los ciudadanos tras el escándalo."},
    {"word":"sólido","type":"adjective","gender":"","definition":"solid, strong, sound","example":"Construyeron una relación sólida basada en la confianza y el respeto."},
    {"word":"sostenible","type":"adjective","gender":"","definition":"sustainable","example":"Necesitamos un modelo económico sostenible para las próximas generaciones."},
    {"word":"urgente","type":"adjective","gender":"","definition":"urgent, pressing","example":"Es urgente encontrar una solución al problema de la escasez hídrica."},
    {"word":"viable","type":"adjective","gender":"","definition":"viable, feasible","example":"El proyecto es técnicamente viable pero requiere una inversión inicial considerable."},
    {"word":"vulnerable","type":"adjective","gender":"","definition":"vulnerable, at risk","example":"Los grupos más vulnerables deben recibir apoyo prioritario del estado."},

    # ── ADVERBS ───────────────────────────────────────────────────────────────
    {"word":"actualmente","type":"adverb","gender":"","definition":"currently, nowadays, at present","example":"Actualmente, más del cincuenta por ciento de la población vive en ciudades."},
    {"word":"aproximadamente","type":"adverb","gender":"","definition":"approximately, roughly","example":"El proyecto costará aproximadamente tres millones de euros en total."},
    {"word":"ciertamente","type":"adverb","gender":"","definition":"certainly, indeed, surely","example":"Ciertamente, la situación es más complicada de lo que parecía inicialmente."},
    {"word":"claramente","type":"adverb","gender":"","definition":"clearly, evidently","example":"El informe señala claramente cuáles son los principales problemas del sistema."},
    {"word":"consecuentemente","type":"adverb","gender":"","definition":"consequently, therefore","example":"Consecuentemente, las medidas adoptadas tuvieron un impacto muy positivo."},
    {"word":"considerablemente","type":"adverb","gender":"","definition":"considerably, significantly","example":"Los precios han subido considerablemente durante el último año."},
    {"word":"constantemente","type":"adverb","gender":"","definition":"constantly, continuously","example":"El mercado cambia constantemente y hay que adaptarse para sobrevivir."},
    {"word":"debidamente","type":"adverb","gender":"","definition":"duly, properly, appropriately","example":"El contrato debe estar debidamente firmado por todas las partes."},
    {"word":"definitivamente","type":"adverb","gender":"","definition":"definitely, finally, conclusively","example":"Definitivamente, este ha sido el mejor año de su carrera profesional."},
    {"word":"drásticamente","type":"adverb","gender":"","definition":"drastically, dramatically","example":"El consumo de agua ha disminuido drásticamente gracias a las nuevas políticas."},
    {"word":"efectivamente","type":"adverb","gender":"","definition":"effectively, indeed","example":"Efectivamente, los datos confirman que la medida tuvo el efecto esperado."},
    {"word":"enormemente","type":"adverb","gender":"","definition":"enormously, greatly, hugely","example":"La experiencia en el extranjero le benefició enormemente a nivel personal."},
    {"word":"especialmente","type":"adverb","gender":"","definition":"especially, particularly","example":"Le gusta leer especialmente los ensayos históricos y los libros de viajes."},
    {"word":"estrictamente","type":"adverb","gender":"","definition":"strictly, purely","example":"Esta información es estrictamente confidencial y no debe compartirse."},
    {"word":"evidentemente","type":"adverb","gender":"","definition":"evidently, obviously","example":"Evidentemente, el problema requería una solución más creativa y profunda."},
    {"word":"finalmente","type":"adverb","gender":"","definition":"finally, ultimately, in the end","example":"Finalmente, llegaron a un acuerdo después de semanas de difíciles negociaciones."},
    {"word":"frecuentemente","type":"adverb","gender":"","definition":"frequently, often","example":"Frecuentemente olvidamos que el descanso es tan importante como el trabajo."},
    {"word":"fundamentalmente","type":"adverb","gender":"","definition":"fundamentally, essentially, basically","example":"El problema es fundamentalmente una cuestión de falta de recursos económicos."},
    {"word":"generalmente","type":"adverb","gender":"","definition":"generally, usually, as a rule","example":"Generalmente, las decisiones más importantes se toman por consenso."},
    {"word":"globalmente","type":"adverb","gender":"","definition":"globally, overall, worldwide","example":"El problema afecta globalmente a todos los países desarrollados."},
    {"word":"gradualmente","type":"adverb","gender":"","definition":"gradually, step by step","example":"La situación fue mejorando gradualmente a lo largo de los meses."},
    {"word":"históricamente","type":"adverb","gender":"","definition":"historically, in historical terms","example":"Históricamente, este tipo de conflictos han durado varios años."},
    {"word":"igualmente","type":"adverb","gender":"","definition":"equally, likewise, also","example":"Igualmente, es importante considerar las consecuencias a largo plazo."},
    {"word":"inmediatamente","type":"adverb","gender":"","definition":"immediately, at once","example":"Hay que actuar inmediatamente para evitar que el problema empeore."},
    {"word":"mayoritariamente","type":"adverb","gender":"","definition":"mostly, predominantly","example":"La población es mayoritariamente favorable a la nueva propuesta legislativa."},
    {"word":"necesariamente","type":"adverb","gender":"","definition":"necessarily, inevitably","example":"Un mayor crecimiento no conlleva necesariamente un mayor bienestar social."},
    {"word":"notablemente","type":"adverb","gender":"","definition":"notably, remarkably, significantly","example":"La calidad del producto ha mejorado notablemente en los últimos meses."},
    {"word":"paulatinamente","type":"adverb","gender":"","definition":"gradually, little by little","example":"La economía se fue recuperando paulatinamente después de la gran crisis."},
    {"word":"principalmente","type":"adverb","gender":"","definition":"mainly, primarily, chiefly","example":"El proyecto está dirigido principalmente a jóvenes de entre quince y veinticinco años."},
    {"word":"progresivamente","type":"adverb","gender":"","definition":"progressively, gradually","example":"La temperatura global ha ido aumentando progresivamente en las últimas décadas."},
    {"word":"profundamente","type":"adverb","gender":"","definition":"deeply, profoundly","example":"La tragedia le afectó profundamente y tardó meses en recuperarse."},
    {"word":"relativamente","type":"adverb","gender":"","definition":"relatively, comparatively","example":"El precio es relativamente barato comparado con otros productos similares."},
    {"word":"significativamente","type":"adverb","gender":"","definition":"significantly, considerably","example":"Las ventas aumentaron significativamente tras la nueva campaña publicitaria."},
    {"word":"simultáneamente","type":"adverb","gender":"","definition":"simultaneously, at the same time","example":"El sistema permite realizar varias operaciones simultáneamente sin problemas."},
    {"word":"sustancialmente","type":"adverb","gender":"","definition":"substantially, significantly","example":"La calidad de vida ha mejorado sustancialmente en los últimos veinte años."},
    {"word":"teóricamente","type":"adverb","gender":"","definition":"theoretically, in theory","example":"Teóricamente el plan es perfecto, pero en la práctica surgen problemas."},
    {"word":"tradicionalmente","type":"adverb","gender":"","definition":"traditionally, conventionally","example":"Tradicionalmente, esta región ha sido conocida por su producción vitivinícola."},
    {"word":"únicamente","type":"adverb","gender":"","definition":"only, solely, exclusively","example":"El acceso está permitido únicamente a personas con acreditación oficial."},
    {"word":"virtualmente","type":"adverb","gender":"","definition":"virtually, practically, almost","example":"Virtualmente todos los expertos coinciden en que la reforma es necesaria."},

    # ── MORE NOUNS ────────────────────────────────────────────────────────────
    {"word":"el acuerdo","type":"noun","gender":"masculine","definition":"agreement, deal, accord","example":"Finalmente firmaron el acuerdo tras meses de intensas negociaciones."},
    {"word":"el alcance","type":"noun","gender":"masculine","definition":"scope, reach, range","example":"El alcance del proyecto es mayor de lo que se pensaba inicialmente."},
    {"word":"el análisis","type":"noun","gender":"masculine","definition":"analysis, examination","example":"El análisis de los datos reveló patrones sorprendentes e inesperados."},
    {"word":"el ámbito","type":"noun","gender":"masculine","definition":"field, scope, area, sphere","example":"En el ámbito laboral, la formación continua es indispensable hoy."},
    {"word":"el carácter","type":"noun","gender":"masculine","definition":"character, nature, personality","example":"Tiene un carácter muy fuerte y es difícil hacerle cambiar de opinión."},
    {"word":"el contexto","type":"noun","gender":"masculine","definition":"context, background","example":"Para entender bien el texto hay que conocer su contexto histórico."},
    {"word":"el contraste","type":"noun","gender":"masculine","definition":"contrast, difference","example":"El contraste entre las dos culturas resultó fascinante e instructivo."},
    {"word":"el desafío","type":"noun","gender":"masculine","definition":"challenge","example":"Aprender a programar fue un gran desafío pero enormemente gratificante."},
    {"word":"el desempleo","type":"noun","gender":"masculine","definition":"unemployment","example":"El desempleo juvenil es uno de los problemas más graves del país."},
    {"word":"el diagnóstico","type":"noun","gender":"masculine","definition":"diagnosis, assessment","example":"El diagnóstico médico tardó varios días en confirmar la enfermedad."},
    {"word":"el diálogo","type":"noun","gender":"masculine","definition":"dialogue, conversation","example":"El diálogo entre las partes fue la clave para resolver el conflicto."},
    {"word":"el dilema","type":"noun","gender":"masculine","definition":"dilemma, difficult choice","example":"Se enfrentó a un difícil dilema entre su carrera y su vida familiar."},
    {"word":"el eje","type":"noun","gender":"masculine","definition":"axis, hub, core","example":"La sostenibilidad es el eje central de la nueva política industrial."},
    {"word":"el enfoque","type":"noun","gender":"masculine","definition":"approach, focus, perspective","example":"El nuevo enfoque pedagógico mejoró los resultados de los alumnos."},
    {"word":"el entorno","type":"noun","gender":"masculine","definition":"environment, surroundings, context","example":"El entorno familiar influye mucho en el desarrollo personal del niño."},
    {"word":"el equilibrio","type":"noun","gender":"masculine","definition":"balance, equilibrium","example":"Mantener el equilibrio entre trabajo y vida personal es muy importante."},
    {"word":"el estándar","type":"noun","gender":"masculine","definition":"standard, norm","example":"Los estándares de calidad de la empresa son reconocidos internacionalmente."},
    {"word":"el flujo","type":"noun","gender":"masculine","definition":"flow, stream","example":"El flujo de información entre departamentos mejoró con el nuevo sistema."},
    {"word":"el impuesto","type":"noun","gender":"masculine","definition":"tax","example":"El gobierno anunció una reducción de impuestos para las pequeñas empresas."},
    {"word":"el indicador","type":"noun","gender":"masculine","definition":"indicator, sign","example":"Los indicadores económicos muestran una recuperación gradual pero sólida."},
    {"word":"el liderazgo","type":"noun","gender":"masculine","definition":"leadership","example":"Su liderazgo fue fundamental para guiar al equipo durante la crisis."},
    {"word":"el límite","type":"noun","gender":"masculine","definition":"limit, boundary, border","example":"Hay que establecer límites claros para evitar conflictos en el trabajo."},
    {"word":"el motivo","type":"noun","gender":"masculine","definition":"reason, motive, cause","example":"No quiso revelar el motivo real de su dimisión ante la prensa."},
    {"word":"el periodo","type":"noun","gender":"masculine","definition":"period, era, time","example":"Durante ese periodo de su vida aprendió muchísimo sobre sí mismo."},
    {"word":"el planteamiento","type":"noun","gender":"masculine","definition":"approach, framing","example":"El planteamiento inicial del problema era demasiado simplista."},
    {"word":"el presupuesto","type":"noun","gender":"masculine","definition":"budget, estimate","example":"El presupuesto para el proyecto fue aprobado por la junta directiva."},
    {"word":"el principio","type":"noun","gender":"masculine","definition":"principle, beginning","example":"Actuó en todo momento de acuerdo con sus principios éticos personales."},
    {"word":"el problema","type":"noun","gender":"masculine","definition":"problem, issue","example":"Identificar el problema es el primer paso para encontrar una solución."},
    {"word":"el progreso","type":"noun","gender":"masculine","definition":"progress, advancement","example":"El progreso tecnológico ha transformado radicalmente la vida cotidiana."},
    {"word":"el rendimiento","type":"noun","gender":"masculine","definition":"performance, yield, output","example":"El rendimiento del equipo mejoró tras los cambios en la gestión."},
    {"word":"el resultado","type":"noun","gender":"masculine","definition":"result, outcome","example":"Los resultados del estudio fueron publicados en una revista científica."},
    {"word":"el ritmo","type":"noun","gender":"masculine","definition":"rhythm, pace, rate","example":"El ritmo de trabajo durante el proyecto fue muy intenso y exigente."},
    {"word":"el valor","type":"noun","gender":"masculine","definition":"value, worth, courage","example":"Los valores éticos son fundamentales en cualquier organización seria."},
    {"word":"la aportación","type":"noun","gender":"feminine","definition":"contribution, input","example":"Su aportación al proyecto fue decisiva para alcanzar el objetivo final."},
    {"word":"la barrera","type":"noun","gender":"feminine","definition":"barrier, obstacle","example":"La barrera del idioma dificulta la integración de muchos inmigrantes."},
    {"word":"la base","type":"noun","gender":"feminine","definition":"base, basis, foundation","example":"Una buena educación es la base de cualquier sociedad próspera."},
    {"word":"la colaboración","type":"noun","gender":"feminine","definition":"collaboration, cooperation","example":"La colaboración entre instituciones mejoró significativamente los resultados."},
    {"word":"la competencia","type":"noun","gender":"feminine","definition":"competition, competence, skill","example":"La competencia en el mercado global obliga a las empresas a innovar."},
    {"word":"la complejidad","type":"noun","gender":"feminine","definition":"complexity","example":"La complejidad del sistema dificulta su comprensión para los usuarios."},
    {"word":"la comunicación","type":"noun","gender":"feminine","definition":"communication","example":"La comunicación efectiva es esencial en cualquier relación interpersonal."},
    {"word":"la condición","type":"noun","gender":"feminine","definition":"condition, requirement, status","example":"Las condiciones del contrato deben ser revisadas antes de la firma."},
    {"word":"la confianza","type":"noun","gender":"feminine","definition":"trust, confidence","example":"La confianza entre los socios es la base de cualquier negocio exitoso."},
    {"word":"la contribución","type":"noun","gender":"feminine","definition":"contribution","example":"Su contribución a la ciencia fue reconocida con el Premio Nobel."},
    {"word":"la coordinación","type":"noun","gender":"feminine","definition":"coordination","example":"La falta de coordinación entre departamentos causó varios problemas."},
    {"word":"la corriente","type":"noun","gender":"feminine","definition":"current, trend, stream","example":"La corriente de pensamiento liberal influyó en la nueva legislación."},
    {"word":"la cultura","type":"noun","gender":"feminine","definition":"culture","example":"La cultura de una nación se refleja en su arte, música y literatura."},
    {"word":"la debilidad","type":"noun","gender":"feminine","definition":"weakness, flaw","example":"Reconocer las propias debilidades es el primer paso para mejorar."},
    {"word":"la dimensión","type":"noun","gender":"feminine","definition":"dimension, aspect, scale","example":"El problema tiene una dimensión social que no debe ignorarse."},
    {"word":"la dinámica","type":"noun","gender":"feminine","definition":"dynamics, workings","example":"La dinámica del mercado laboral ha cambiado radicalmente en los últimos años."},
    {"word":"la educación","type":"noun","gender":"feminine","definition":"education","example":"La educación de calidad es un derecho fundamental de todos los niños."},
    {"word":"la expectativa","type":"noun","gender":"feminine","definition":"expectation","example":"Las expectativas de los inversores son muy altas para el próximo trimestre."},
    {"word":"la experiencia","type":"noun","gender":"feminine","definition":"experience","example":"La experiencia adquirida en ese trabajo fue muy valiosa para su carrera."},
    {"word":"la financiación","type":"noun","gender":"feminine","definition":"financing, funding","example":"La financiación del proyecto depende de la aprobación del presupuesto."},
    {"word":"la función","type":"noun","gender":"feminine","definition":"function, role, duty","example":"La función principal del gobierno es garantizar el bienestar de los ciudadanos."},
    {"word":"la generación","type":"noun","gender":"feminine","definition":"generation","example":"Las nuevas generaciones tienen una mayor conciencia ambiental que las anteriores."},
    {"word":"la herramienta","type":"noun","gender":"feminine","definition":"tool, instrument","example":"Internet se ha convertido en una herramienta indispensable de trabajo."},
    {"word":"la información","type":"noun","gender":"feminine","definition":"information","example":"Acceder a información veraz y contrastada es un derecho fundamental."},
    {"word":"la institución","type":"noun","gender":"feminine","definition":"institution","example":"Las instituciones democráticas deben ser transparentes y responsables."},
    {"word":"la integración","type":"noun","gender":"feminine","definition":"integration","example":"La integración cultural requiere esfuerzo por parte de toda la sociedad."},
    {"word":"la inversión","type":"noun","gender":"feminine","definition":"investment","example":"La inversión en investigación y desarrollo es vital para la competitividad."},
    {"word":"la legislación","type":"noun","gender":"feminine","definition":"legislation, law","example":"La nueva legislación busca proteger mejor los datos personales de los usuarios."},
    {"word":"la limitación","type":"noun","gender":"feminine","definition":"limitation, restriction","example":"Las limitaciones presupuestarias impidieron ampliar el programa social."},
    {"word":"la mentalidad","type":"noun","gender":"feminine","definition":"mentality, mindset","example":"Se necesita un cambio de mentalidad para abordar los problemas actuales."},
    {"word":"la movilidad","type":"noun","gender":"feminine","definition":"mobility","example":"La movilidad social ha disminuido en muchos países desarrollados."},
    {"word":"la naturaleza","type":"noun","gender":"feminine","definition":"nature","example":"La naturaleza del problema exige una solución urgente y coordinada."},
    {"word":"la necesidad","type":"noun","gender":"feminine","definition":"need, necessity","example":"La necesidad de cambio fue reconocida por todos los miembros del comité."},
    {"word":"la oportunidad","type":"noun","gender":"feminine","definition":"opportunity, chance","example":"Esta es una oportunidad única para demostrar tu talento y capacidad."},
    {"word":"la participación","type":"noun","gender":"feminine","definition":"participation, involvement","example":"La participación ciudadana en la política es esencial en democracia."},
    {"word":"la planificación","type":"noun","gender":"feminine","definition":"planning","example":"Una buena planificación es clave para el éxito de cualquier proyecto."},
    {"word":"la población","type":"noun","gender":"feminine","definition":"population","example":"La población mundial superará los diez mil millones para el año dos mil cincuenta."},
    {"word":"la posición","type":"noun","gender":"feminine","definition":"position, stance","example":"La posición del gobierno ante la crisis fue criticada por la oposición."},
    {"word":"la preocupación","type":"noun","gender":"feminine","definition":"concern, worry","example":"La preocupación por el cambio climático aumenta entre los ciudadanos."},
    {"word":"la productividad","type":"noun","gender":"feminine","definition":"productivity","example":"La productividad del equipo mejoró tras la implementación del nuevo método."},
    {"word":"la proyección","type":"noun","gender":"feminine","definition":"projection, forecast","example":"Las proyecciones económicas para el próximo año son moderadamente optimistas."},
    {"word":"la regulación","type":"noun","gender":"feminine","definition":"regulation","example":"La regulación del sector financiero se reforzó tras la última crisis."},
    {"word":"la relación","type":"noun","gender":"feminine","definition":"relationship, relation","example":"La relación entre economía y bienestar social es compleja y multifacética."},
    {"word":"la rentabilidad","type":"noun","gender":"feminine","definition":"profitability, return","example":"La rentabilidad del proyecto mejoró gracias a la reducción de costes."},
    {"word":"la sociedad","type":"noun","gender":"feminine","definition":"society","example":"La sociedad debe adaptarse a los cambios tecnológicos de manera responsable."},
    {"word":"la solución","type":"noun","gender":"feminine","definition":"solution","example":"Encontrar una solución duradera al conflicto requiere voluntad política."},
    {"word":"la sostenibilidad","type":"noun","gender":"feminine","definition":"sustainability","example":"La sostenibilidad del planeta depende de nuestras decisiones actuales."},
    {"word":"la tensión","type":"noun","gender":"feminine","definition":"tension, stress","example":"La tensión entre las dos naciones aumentó tras el incidente diplomático."},
    {"word":"la trayectoria","type":"noun","gender":"feminine","definition":"trajectory, career path","example":"Su trayectoria profesional es un ejemplo de dedicación y trabajo constante."},
    {"word":"la urbanización","type":"noun","gender":"feminine","definition":"urbanization","example":"La urbanización acelerada plantea nuevos retos para las ciudades modernas."},

    # ── MORE VERBS ────────────────────────────────────────────────────────────
    {"word":"acometer","type":"verb","gender":"","definition":"to undertake, tackle, take on","example":"El equipo decidió acometer el proyecto con entusiasmo y determinación."},
    {"word":"agudizar","type":"verb","gender":"","definition":"to sharpen, intensify, worsen","example":"La crisis económica agudizó las desigualdades sociales existentes."},
    {"word":"anticipar","type":"verb","gender":"","definition":"to anticipate, foresee","example":"Nadie pudo anticipar el impacto tan grande que tendría la pandemia."},
    {"word":"articular","type":"verb","gender":"","definition":"to articulate, coordinate, link","example":"El plan articula medidas económicas y sociales de forma coherente."},
    {"word":"catalizar","type":"verb","gender":"","definition":"to catalyze, trigger, accelerate","example":"El discurso catalizó el debate sobre la reforma constitucional."},
    {"word":"ceder","type":"verb","gender":"","definition":"to yield, give way, hand over","example":"Tuvo que ceder ante las presiones del comité ejecutivo."},
    {"word":"cimentar","type":"verb","gender":"","definition":"to lay the foundation, cement","example":"Los primeros años de vida cimentan la personalidad del individuo."},
    {"word":"conciliar","type":"verb","gender":"","definition":"to reconcile, balance, conciliate","example":"Es difícil conciliar las exigencias laborales con la vida familiar."},
    {"word":"condicionar","type":"verb","gender":"","definition":"to condition, influence, determine","example":"El entorno social condiciona enormemente el desarrollo personal."},
    {"word":"confrontar","type":"verb","gender":"","definition":"to confront, face, compare","example":"Hay que confrontar los datos de diferentes fuentes para verificarlos."},
    {"word":"demandar","type":"verb","gender":"","definition":"to demand, require, sue","example":"El puesto demanda una gran capacidad de liderazgo y trabajo en equipo."},
    {"word":"desencadenar","type":"verb","gender":"","definition":"to trigger, unleash, set off","example":"La crisis financiera desencadenó una ola de protestas sociales."},
    {"word":"detectar","type":"verb","gender":"","definition":"to detect, identify, spot","example":"El sistema detectó el problema antes de que causara daños graves."},
    {"word":"diferenciar","type":"verb","gender":"","definition":"to differentiate, distinguish","example":"Hay que diferenciar entre los datos reales y las estimaciones."},
    {"word":"dimensionar","type":"verb","gender":"","definition":"to size, assess the scale of","example":"Es importante dimensionar correctamente el alcance del proyecto."},
    {"word":"ejercer","type":"verb","gender":"","definition":"to exercise, practice, exert","example":"Lleva veinte años ejerciendo como médico en el hospital público."},
    {"word":"enfocar","type":"verb","gender":"","definition":"to focus, approach","example":"Decidieron enfocar el problema desde una perspectiva más práctica."},
    {"word":"enriquecer","type":"verb","gender":"","definition":"to enrich, enhance","example":"Viajar enriquece la mente y amplía la visión del mundo."},
    {"word":"erradicar","type":"verb","gender":"","definition":"to eradicate, eliminate","example":"El objetivo es erradicar la pobreza extrema en los próximos años."},
    {"word":"esclarecer","type":"verb","gender":"","definition":"to clarify, shed light on","example":"La investigación ayudó a esclarecer los hechos del suceso."},
    {"word":"exhibir","type":"verb","gender":"","definition":"to exhibit, display, show","example":"El museo exhibirá las obras restauradas a partir del próximo mes."},
    {"word":"facilitar","type":"verb","gender":"","definition":"to facilitate, make easier","example":"La tecnología facilita el acceso a la información desde cualquier lugar."},
    {"word":"fundamentar","type":"verb","gender":"","definition":"to base, ground, substantiate","example":"Fundamentó su argumento en datos estadísticos muy precisos."},
    {"word":"inducir","type":"verb","gender":"","definition":"to induce, lead to, cause","example":"El estrés crónico puede inducir problemas de salud graves."},
    {"word":"instaurar","type":"verb","gender":"","definition":"to establish, introduce, set up","example":"El nuevo gobierno instauró una política de transparencia institucional."},
    {"word":"limitar","type":"verb","gender":"","definition":"to limit, restrict, constrain","example":"Los recursos económicos limitaron el alcance del programa social."},
    {"word":"marcar","type":"verb","gender":"","definition":"to mark, set, define","example":"Ese momento marcó un antes y un después en su carrera profesional."},
    {"word":"matizar","type":"verb","gender":"","definition":"to qualify, nuance, shade","example":"Hay que matizar esa afirmación tan categórica con más datos."},
    {"word":"minimizar","type":"verb","gender":"","definition":"to minimize, reduce","example":"El objetivo es minimizar el impacto ambiental de la producción industrial."},
    {"word":"movilizar","type":"verb","gender":"","definition":"to mobilize, rally","example":"La causa logró movilizar a miles de personas en todo el país."},
    {"word":"optimizar","type":"verb","gender":"","definition":"to optimize, improve","example":"La empresa invirtió en tecnología para optimizar sus procesos productivos."},
    {"word":"paliar","type":"verb","gender":"","definition":"to alleviate, mitigate, relieve","example":"Las nuevas medidas buscan paliar los efectos de la crisis económica."},
    {"word":"percibir","type":"verb","gender":"","definition":"to perceive, notice, receive","example":"Se percibe un cambio positivo en el ambiente laboral de la empresa."},
    {"word":"persistir","type":"verb","gender":"","definition":"to persist, continue, remain","example":"Los problemas estructurales persisten a pesar de las reformas realizadas."},
    {"word":"prever","type":"verb","gender":"","definition":"to foresee, anticipate, plan for","example":"Nadie pudo prever las consecuencias tan graves de aquella decisión."},
    {"word":"priorizar","type":"verb","gender":"","definition":"to prioritize","example":"El gobierno debe priorizar la educación y la sanidad en los presupuestos."},
    {"word":"racionalizar","type":"verb","gender":"","definition":"to rationalize, streamline","example":"Decidieron racionalizar los recursos para reducir los costes operativos."},
    {"word":"reforzar","type":"verb","gender":"","definition":"to reinforce, strengthen","example":"Es necesario reforzar las medidas de seguridad ante las nuevas amenazas."},
    {"word":"replantear","type":"verb","gender":"","definition":"to reconsider, rethink","example":"Los resultados negativos obligaron al equipo a replantear la estrategia."},
    {"word":"respaldar","type":"verb","gender":"","definition":"to support, back, endorse","example":"La mayoría parlamentaria respaldó la nueva propuesta de ley."},
    {"word":"restringir","type":"verb","gender":"","definition":"to restrict, limit","example":"Las nuevas medidas restringen el acceso a determinadas zonas urbanas."},
    {"word":"retomar","type":"verb","gender":"","definition":"to resume, take up again","example":"Tras las vacaciones, retomaron las negociaciones con nuevas propuestas."},
    {"word":"salvaguardar","type":"verb","gender":"","definition":"to safeguard, protect","example":"Es necesario salvaguardar los derechos fundamentales de todos los ciudadanos."},
    {"word":"sintetizar","type":"verb","gender":"","definition":"to synthesize, summarize","example":"El informe sintetiza los resultados de dos años de investigación."},
    {"word":"subrayar","type":"verb","gender":"","definition":"to underline, emphasize, stress","example":"El director subrayó la importancia de respetar los plazos establecidos."},
    {"word":"suscitar","type":"verb","gender":"","definition":"to arouse, provoke, give rise to","example":"La propuesta suscitó un intenso debate entre los miembros del comité."},
    {"word":"tender a","type":"verb","gender":"","definition":"to tend to, be inclined to","example":"Las personas tienden a buscar información que confirme sus creencias."},
    {"word":"trascender","type":"verb","gender":"","definition":"to transcend, go beyond","example":"El impacto de su obra trascendió las fronteras nacionales."},

    # ── MORE ADJECTIVES ───────────────────────────────────────────────────────
    {"word":"adyacente","type":"adjective","gender":"","definition":"adjacent, neighboring","example":"El edificio adyacente fue demolido para construir un parque público."},
    {"word":"asequible","type":"adjective","gender":"","definition":"affordable, accessible, attainable","example":"El objetivo es hacer la vivienda más asequible para los jóvenes."},
    {"word":"autónomo","type":"adjective","gender":"","definition":"autonomous, independent, self-employed","example":"Trabaja como consultor autónomo desde hace más de diez años."},
    {"word":"cauteloso","type":"adjective","gender":"","definition":"cautious, careful, wary","example":"Fue muy cauteloso antes de tomar una decisión tan importante."},
    {"word":"coherente","type":"adjective","gender":"","definition":"coherent, consistent","example":"Sus acciones deben ser coherentes con los valores que defiende."},
    {"word":"colectivo","type":"adjective","gender":"","definition":"collective, shared, group","example":"La responsabilidad colectiva es esencial para proteger el medio ambiente."},
    {"word":"compatible","type":"adjective","gender":"","definition":"compatible, consistent with","example":"Sus ideas son completamente compatibles con los objetivos del proyecto."},
    {"word":"competitivo","type":"adjective","gender":"","definition":"competitive","example":"Para mantenerse competitivo hay que innovar y adaptarse constantemente."},
    {"word":"completo","type":"adjective","gender":"","definition":"complete, full, thorough","example":"El análisis completo del problema tardó más de un mes en realizarse."},
    {"word":"convergente","type":"adjective","gender":"","definition":"convergent","example":"Los objetivos de ambas partes resultaron ser bastante convergentes."},
    {"word":"credible","type":"adjective","gender":"","definition":"credible, believable","example":"Para que la propuesta sea creíble, debe estar respaldada por datos."},
    {"word":"dinámico","type":"adjective","gender":"","definition":"dynamic, energetic","example":"Es un sector muy dinámico que cambia constantemente con la tecnología."},
    {"word":"emergente","type":"adjective","gender":"","definition":"emerging, rising","example":"Los mercados emergentes ofrecen grandes oportunidades de inversión."},
    {"word":"estable","type":"adjective","gender":"","definition":"stable, steady","example":"La economía del país se mantiene estable gracias a las reformas."},
    {"word":"estructural","type":"adjective","gender":"","definition":"structural","example":"Los problemas estructurales requieren reformas profundas y a largo plazo."},
    {"word":"factible","type":"adjective","gender":"","definition":"feasible, achievable","example":"El proyecto es perfectamente factible con los recursos disponibles."},
    {"word":"fiable","type":"adjective","gender":"","definition":"reliable, trustworthy","example":"Necesitamos fuentes de información fiables para tomar buenas decisiones."},
    {"word":"frágil","type":"adjective","gender":"","definition":"fragile, delicate, vulnerable","example":"La paz alcanzada sigue siendo frágil y necesita consolidarse."},
    {"word":"holístico","type":"adjective","gender":"","definition":"holistic","example":"Se adoptó un enfoque holístico para abordar el problema de salud pública."},
    {"word":"incipiente","type":"adjective","gender":"","definition":"incipient, emerging, budding","example":"La incipiente industria tecnológica del país muestra un gran potencial."},
    {"word":"indispensable","type":"adjective","gender":"","definition":"indispensable, essential","example":"La colaboración es indispensable para alcanzar los objetivos del proyecto."},
    {"word":"inherente","type":"adjective","gender":"","definition":"inherent, intrinsic","example":"Los riesgos inherentes a esta actividad deben ser gestionados cuidadosamente."},
    {"word":"latente","type":"adjective","gender":"","definition":"latent, hidden, underlying","example":"El conflicto latente entre los grupos estalló finalmente en verano."},
    {"word":"legítimo","type":"adjective","gender":"","definition":"legitimate, lawful, rightful","example":"Es legítimo exigir mejores condiciones laborales para todos los trabajadores."},
    {"word":"marginal","type":"adjective","gender":"","definition":"marginal, minor, fringe","example":"El impacto fue marginal y no alteró significativamente los resultados globales."},
    {"word":"momentáneo","type":"adjective","gender":"","definition":"momentary, temporary","example":"La mejora fue momentánea y los problemas regresaron rápidamente."},
    {"word":"múltiple","type":"adjective","gender":"","definition":"multiple, various","example":"Los múltiples factores que contribuyen al problema deben ser considerados."},
    {"word":"mutuo","type":"adjective","gender":"","definition":"mutual, reciprocal","example":"El respeto mutuo es la base de cualquier convivencia pacífica y duradera."},
    {"word":"parcial","type":"adjective","gender":"","definition":"partial, biased, incomplete","example":"El análisis parcial de los datos puede llevar a conclusiones erróneas."},
    {"word":"permanente","type":"adjective","gender":"","definition":"permanent, lasting","example":"El objetivo es establecer una solución permanente al problema hídrico."},
    {"word":"pertinente","type":"adjective","gender":"","definition":"pertinent, relevant, appropriate","example":"Sus comentarios fueron muy pertinentes y ayudaron a mejorar el informe."},
    {"word":"pionero","type":"adjective","gender":"","definition":"pioneering, groundbreaking","example":"Fue una empresa pionera en el uso de energías renovables en el sector."},
    {"word":"potencial","type":"adjective","gender":"","definition":"potential, possible","example":"Los clientes potenciales del producto son principalmente jóvenes profesionales."},
    {"word":"previo","type":"adjective","gender":"","definition":"previous, prior, preliminary","example":"Se requiere una autorización previa para acceder a los archivos históricos."},
    {"word":"recurrente","type":"adjective","gender":"","definition":"recurring, recurrent","example":"Los errores recurrentes indican un problema sistémico que hay que resolver."},
    {"word":"reformista","type":"adjective","gender":"","definition":"reformist","example":"El partido tiene una agenda claramente reformista en materia económica."},
    {"word":"renovable","type":"adjective","gender":"","definition":"renewable","example":"La inversión en energías renovables es indispensable para el futuro."},
    {"word":"resiliente","type":"adjective","gender":"","definition":"resilient","example":"La comunidad se mostró resiliente ante la catástrofe natural."},
    {"word":"restrictivo","type":"adjective","gender":"","definition":"restrictive, limiting","example":"Las medidas restrictivas afectaron gravemente a los pequeños comercios."},
    {"word":"rotundo","type":"adjective","gender":"","definition":"resounding, emphatic, complete","example":"El fracaso fue rotundo y nadie en el equipo quería hablar del tema."},
    {"word":"sistemático","type":"adjective","gender":"","definition":"systematic, methodical","example":"El análisis sistemático de los datos permitió identificar el problema."},
    {"word":"subjetivo","type":"adjective","gender":"","definition":"subjective","example":"La percepción del riesgo es subjetiva y varía mucho según la persona."},
    {"word":"subyacente","type":"adjective","gender":"","definition":"underlying","example":"El problema subyacente no se abordó adecuadamente en la reunión."},
    {"word":"tangible","type":"adjective","gender":"","definition":"tangible, concrete","example":"Los resultados tangibles del programa fueron muy positivos para la comunidad."},
    {"word":"unánime","type":"adjective","gender":"","definition":"unanimous","example":"La decisión fue unánime y todos los miembros apoyaron la propuesta."},
]
